### PR TITLE
RATEST-296:E2E Test: Visit feature workflow

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-296

### CODE REVIEW

**Comment by kdaud** [comment]
any progress with this work?

**Comment by sherrif10** [comment]
Ohh sorry. Finishing it soon today probably.

**Comment by kdaud** [comment]
@sherrif10 are you still working on this PR? or the  ticket can be pushed back for Ready For Work so that any one can pick it up!

**Comment by sherrif10** [comment]
Someone is working on this ticket.

**Pull request closed without merging**
