### PR TITLE
README: Get rid of tracking already developed workflow tests as under development, and Add a text 'Workflow Tests' on 3.x RefApp

### PR DESCRIPTION
**Pull request by kdaud**
Summary:
- Update the read me file

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 take a look on the commit for recommendation !

**Review by sherrif10 — APPROVED** [review]
Thanks @kdaud . cc @dkayiwa fair enough to merge

**Comment by dkayiwa** [comment]
What kind of update are you making to the readme file?

**Comment by kdaud** [comment]
> What kind of update are you making to the readme file?

Some two tests that are being tracked on our Dashboard as under development are already developed and running in master.

As well its a good idea to rename 3.x RefApp to 3.x RefApp Automated Tests

**Comment by dkayiwa** [comment]
A summary of the updates would serve as a better commit message than simply saying Update the readme file.

**Comment by kdaud** [comment]
> A summary of the updates would serve as a better commit message than simply saying Update the readme file.

Done with love !

cc: @dkayiwa

**Comment by dkayiwa** [comment]
`Commit Message`

**Comment by kdaud** [comment]
@dkayiwa have put the summary under the description section of the PR.

**Comment by dkayiwa** [comment]
That is longer than a summary

**Comment by kdaud** [comment]
> That is longer than a summary

It now smart, check and see how beautiful its now.

**Comment by dkayiwa** [comment]
Still too long. Actually much longer than the actual changes.

**Comment by kdaud** [comment]
> Still too long. Actually much longer than the actual changes.

Its now shorter and I think you will love it, check again and see its beauty

**Pull request merged**
