### PR TITLE
create admit patient test

### PR DESCRIPTION
**Pull request by gracebish**
create admitPatient.yml file

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @gracebish  do you have any ticket id for this?

**Comment by sherrif10** [comment]
We might not neccesariy need to define the whole configuration of the hook , we only need to use the already defined @selenium hook, by doing this config, we are introducing an E2E  test based workflow and creating a new run method.

**Comment by kdaud** [comment]
@gracebish provide the ticket url to this commit.

**Comment by gracebish** [comment]
Thank you @sherrif10. Let me close this.

**Pull request closed without merging**
