### PR TITLE
Bumb firefox driver to v94

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by kdaud** [comment]
@dkayiwa we can have this merged and I follow up on the failing tests to fix them accordingly.

**Review by sherrif10 — COMMENTED** [review]
Is this the latest driver of firefox

**Comment by kdaud** [comment]
> Is this the latest driver of firefox

yes! checkout at https://github.com/mozilla/geckodriver/releases

**Review by sherrif10 — APPROVED** [review]
Thank @kdaud

**Comment by sherrif10** [comment]
i think this is where https://github.com/openmrs/openmrs-contrib-qaframework/pull/328  will add more value to our  workflows. one  thing this ticket will resolve is to do with drivers. we will nolonger deal with either local drivers or configured drivers. Let me find time and finish that work.

**Comment by sherrif10** [comment]
@kdaud  does this resolve the issue with our drivers locally

**Comment by kdaud** [comment]
> @kdaud does this resolve the issue with our drivers locally

Locally one has to download a driver that is compatible with a browser version running on the machine.

**Comment by sherrif10** [comment]
> > @kdaud does this resolve the issue with our drivers locally
> 
> Locally one has to download a driver that is compatible with a browser version running on the machine.

Makes sense.

**Pull request merged**
