### PR TITLE
RATEST-227: Adding event handler for the 3.x refapp workflow tests

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-227)

Description -> 3.x RefApp workflow tests are failing due to an error, unhandled promise rejection

### CODE REVIEW

**Comment by kdaud** [comment]
Waiting for review cc: @sherrif10

**Comment by ibacher** [comment]
@kdaud I think it's cleaner to do this:

```js
Before(() =>
  cy.on('uncaught:exception', (err, runnable) => {
    console.log(err);
    return false;
  }
));
```

**Comment by ibacher** [comment]
@kdaud Fair enough... I guess we should revert back to your original version.

**Comment by kdaud** [comment]
> I guess we should revert back to your original version.


`Boolean isTheCommitRevertedBackToOriginVersion = true`

cc: @ibacher

**Comment by kdaud** [comment]
I know @ibacher is about to take a final review on this commit to have our 3.x refapp test up and running!

**Review by ibacher — APPROVED** [review]

**Pull request merged**
