### PR TITLE
O3-993 : Fix RefApp 3.x login E2E test

### PR DESCRIPTION
**Pull request by pasindur99**
## Purpose
The purpose of this PR is to fix [O3-993](https://issues.openmrs.org/browse/O3-993)

## Goals
Fix the failing login E2E test.

## Approach
Update relevant cypress environment variables.
Updated the login E2E test and workflow

## Screenshots
image

Note: The error message with the wrong login details is not shown in the UI. Because of it 2 of 3 tests are failing.

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
@pasindur99 , the login workflow is not running properly. I think that is because the directory structure has been changed. You should update the workflow file in that case.

**Comment by pasindur99** [comment]
Thank you @jayasanka-sack for reviewing the pr. I'll update the workflows and let you know.

**Review by jayasanka-sack — APPROVED** [review]
Thanks for getting this, done @pasindur99 !!

**Comment by jayasanka-sack** [comment]
Merging as the relevant tests passing (one test fails because of a bug in the app)

**Pull request merged**
