### PR TITLE
RATEST-330: Fix delete resource within rest client call

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-330)

Description -> Fix delete patient within rest client call

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud  Weldone, some errors on All firefox to look at.

**Comment by kdaud** [comment]
@sherrif10 am done with fixing the root cause. So we are good to go -->

**Comment by dkayiwa** [comment]
@kdaud how does just catching and ignoring the exception fix the problem?

**Comment by kdaud** [comment]
Here is the context:

The tests are failing to delete the resource(testPateint) at the end of the run probably due to Rest client call responsible to for the operation. 

> java.lang.IllegalStateException: Delete request failed: https://qa-refapp.openmrs.org/openmrs/ws/rest/v1/patient/b831a4d2-a64f-4c5b-a291-1b85f39272f3

The logs are similar and signals that RestClient.delete() is being invoked at an illegal or inappropriate time. In other words, the Java environment or Java application is not in an appropriate state for the requested operation. So adding the try catch makes the operation succeed.

**Comment by dkayiwa** [comment]
Shouldn't we just fix the cause of the exception? What you have done in this pull request is taking the whistle blower to prison instead of using their information to find the culprit.

**Comment by kdaud** [comment]
> What you have done in this pull request is taking the whistle blower to prison instead of using their information to find the culprit.

Have embarked on using their information to find the exact culprit and then deal with him as the law states.

**Comment by sherrif10** [comment]
@kdaud Are we still interested in these changes.

**Comment by kdaud** [comment]
The snag is fixed.

**Pull request closed without merging**
