### PR TITLE
RATEST-259: Format qaframework module with selenium formatter

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-259   cc @kdaud  what do you think of these changes, in regard to this https://github.com/openmrs/openmrs-contrib-qaframework/pull/180

This pull request is for formating code to look more cleaner, the problem that it is addressing is auto formatting the code immediately when it gets cloned. By default this change will be made by default for ever ide after it gets cloned

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 put a description of what is being done in this PR including the problem it is addressing!

**Comment by sherrif10** [comment]
Sure @kdaud  since this does the same thing as what you had started , will update it the same way. Thanks

**Comment by kdaud** [comment]
@sherrif10 you seem to have done something different, revisit the comment [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/205#issuecomment-958991074)!

**Comment by sherrif10** [comment]
Have to update the description, @kdaud , Look through the description.

**Comment by kdaud** [comment]
@sherrif10 is there any configuration that has been made to address the issue?

**Comment by sherrif10** [comment]
@kdaud  configurations have been made on ide and to confirm with that, changes are no longer behaving the weird way.

**Comment by kdaud** [comment]
@sherrif10 have tested these changes locally but seems not to yield what we intend to achieve, am investigating why the issue happens on local build plans and will soon rise a PR that will have a solution to override the selenium-cucumber formatter on local build plans!

**Comment by sherrif10** [comment]
> @sherrif10 have tested these changes locally but seems not to yield what we intend to achieve, am investigating why the issue happens on local build plans and will soon rise a PR that will have a solution to override the selenium-cucumber formatter on local build plans!

How have you tested these changes locally ?

**Comment by sherrif10** [comment]
> a PR that will have a solution to override the selenium-cucumber formatter on local build plans!

Sounds good deal. Eagerly waiting

**Comment by kdaud** [comment]
have fixed the issue within `pull/180`

**Comment by kdaud** [comment]
@sherrif10 do you  mind if we have this PR closed since the issue it's addressing was covered in this [commit](https://github.com/openmrs/openmrs-contrib-qaframework/commit/2c6702e124832a5ae716ea61b50db08399919af0)?

**Comment by sherrif10** [comment]
Thanks

**Pull request closed without merging**
