### PR TITLE
Debugging: Fork of Jayasanka's RATEST-169

### PR DESCRIPTION
**Pull request by brandones**
Just for debugging purposes.

### CODE REVIEW

**Comment by brandones** [comment]
Okay, following @ibacher 's advice I added a step to make it upload the openmrs.log as an artifact. That's here:

[openmrs.log](https://github.com/openmrs/openmrs-contrib-qaframework/files/6927485/openmrs.log)

The latter part of which reads

```
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,003| Exiting method saveConceptSource
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,027| In method PatientService.savePatientIdentifierType. Arguments: PatientIdentifierType=OpenMRS ID, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,044| Exiting method savePatientIdentifierType
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,080| In method MetadataMappingService.saveMetadataTermMapping. Arguments: MetadataTermMapping=MetadataTermMapping[hashCode=308efb93,uuid=ef645595-2b95-4bfc-8aaa-33f95ec132c5], 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,086| Exiting method saveMetadataTermMapping
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,096| In method ConceptService.purgeConceptClass. Arguments: ConceptClass=ConceptClass[hashCode=a7612e8c,uuid=8e071bfe-520c-44c0-a89b-538e9129b42a], 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,104| Exiting method purgeConceptClass
WARN - AbstractTableMetaData.getDataTypeFactory(166) |2021-08-03 22:40:31,219| Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
WARN - AbstractTableMetaData.getDataTypeFactory(166) |2021-08-03 22:40:31,227| Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
WARN - AbstractTableMetaData.getDataTypeFactory(166) |2021-08-03 22:40:31,237| Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
WARN - AbstractTableMetaData.getDataTypeFactory(166) |2021-08-03 22:40:31,355| Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products.
WARN - ModuleUtil.refreshApplicationContext(936) |2021-08-03 22:40:31,367| Unable to invoke started() method on the module's activator
java.lang.RuntimeException: java.sql.SQLException: Incorrect string value: '\xDA\xA9\xD8\xB3\xDB\x8C...' for column 'description' at row 1
	at org.openmrs.module.dataexchange.DataImporter.importData(DataImporter.java:87)
	at org.openmrs.module.dataexchange.DataImporter$1.execute(DataImporter.java:51)
	at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:54)
	at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:2076)
	at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:2073)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:313)
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2095)
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2080)
	at org.openmrs.api.db.hibernate.DbSession.doWork(DbSession.java:1005)
	at org.openmrs.module.dataexchange.DataImporter.importData(DataImporter.java:49)
	at org.openmrs.module.dataexchange.DataImporter$$FastClassBySpringCGLIB$$572a80f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.openmrs.module.dataexchange.DataImporter$$EnhancerBySpringCGLIB$$fa077184.importData(<generated>)
	at org.openmrs.module.referencemetadata.ReferenceMetadataActivator.installConcepts(ReferenceMetadataActivator.java:96)
	at org.openmrs.module.referencemetadata.ReferenceMetadataActivator.started(ReferenceMetadataActivator.java:62)
	at org.openmrs.module.ModuleUtil.refreshApplicationContext(ModuleUtil.java:928)
	at org.openmrs.module.web.WebModuleUtil.refreshWAC(WebModuleUtil.java:847)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:632)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:612)
	at org.openmrs.web.Listener.startOpenmrs(Listener.java:251)
	at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:42)
Caused by: java.sql.SQLException: Incorrect string value: '\xDA\xA9\xD8\xB3\xDB\x8C...' for column 'description' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:823)
	at org.dbunit.database.statement.SimplePreparedStatement.addBatch(SimplePreparedStatement.java:80)
	at org.dbunit.operation.RefreshOperation$RowOperation.execute(RefreshOperation.java:183)
	at org.dbunit.operation.RefreshOperation$InsertRowOperation.execute(RefreshOperation.java:249)
	at org.dbunit.operation.RefreshOperation.execute(RefreshOperation.java:112)
	at org.openmrs.module.dataexchange.DataImporter.importData(DataImporter.java:81)
	... 27 more
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,643| In method LocationService.saveLocationTag. Arguments: LocationTag=Login Location, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,650| Exiting method saveLocationTag
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,684| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,715| Exiting method saveConcept
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,726| In method ConceptService.saveConcept. Arguments: Concept=Concept #null, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,754| Exiting method saveConcept
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,765| In method EncounterService.saveEncounterType. Arguments: EncounterType=EncounterType[hashCode=705571f2,uuid=5021b1a1-e7f6-44b4-ba02-da2f2bcf8718], 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,779| Exiting method saveEncounterType
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,807| In method AProperty. Arguments: GlobalProperty=property: registrationcore.identifierSourceId value: 1, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,812| Exiting method saveGlobalProperty
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,853| In method DefinitionService.saveDefinition. Arguments: Definition=appointmentschedulingui.appointmentDataSetDefinition.dailyAppointments, 
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,857| In method SerializedDefinitionService.saveDefinition. Arguments: Definition=appointmentschedulingui.appointmentDataSetDefinition.dailyAppointments, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,931| Exiting method saveDefinition
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,931| Exiting method saveDefinition
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,976| In method AdministrationService.saveGlobalProperty. Arguments: GlobalProperty=property: registrationcore.patientNameSearch value: registrationcore.ExistingPatientNameSearch, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,982| Exiting method saveGlobalProperty
INFO - LoggingAdvice.invoke(116) |2021-08-03 22:40:31,992| In method AdministrationService.saveGlobalProperty. Arguments: GlobalProperty=property: referenceapplication.started value: false, 
INFO - LoggingAdvice.invoke(156) |2021-08-03 22:40:31,997| Exiting method saveGlobalProperty
WARN - ModuleUtil.refreshApplicationContext(936) |2021-08-03 22:40:32,017| Unable to invoke started() method on the module's activator
java.lang.RuntimeException: failed to setup the required modules
	at org.openmrs.module.referenceapplication.ReferenceApplicationActivator.started(ReferenceApplicationActivator.java:116)
	at org.openmrs.module.ModuleUtil.refreshApplicationContext(ModuleUtil.java:928)
	at org.openmrs.module.web.WebModuleUtil.refreshWAC(WebModuleUtil.java:847)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:632)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:612)
	at org.openmrs.web.Listener.startOpenmrs(Listener.java:251)
	at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:42)
Caused by: java.lang.NullPointerException
	at org.openmrs.module.referenceapplication.ReferenceApplicationActivator.mapMetadata(ReferenceApplicationActivator.java:150)
	at org.openmrs.module.referenceapplication.ReferenceApplicationActivator.setupEmrApiGlobalProperties(ReferenceApplicationActivator.java:131)
	at org.openmrs.module.referenceapplication.ReferenceApplicationActivator.started(ReferenceApplicationActivator.java:102)
	... 6 more
ERROR - CommonsLoggingOutput.error(75) |2021-08-03 22:40:34,278| Line=362 The content of element type "dwr" must match "(init?,allow?,signatures?)".
ERROR - CommonsLoggingOutput.error(75) |2021-08-03 22:40:34,283| Parameter mismatch parsing signatures section in dwr.xml on line: DWRAtlasService.disableAtlasModule()
ERROR - CommonsLoggingOutput.error(75) |2021-08-03 22:40:34,285| Parameter mismatch parsing signatures section in dwr.xml on line: DWRHtmlFormEntryService.checkIfLoggedIn()
WARN - OpenmrsUtil.getRuntimePropertiesFilePathName(2078) |2021-08-03 22:40:34,309| Unable to find a runtime properties file at /usr/local/tomcat/openmrs-runtime.properties
```

When running these containers in docker compose, they come up just fine, no errors.

Here's [ReferenceApplicationActivator.java:150](https://github.com/openmrs/openmrs-module-referenceapplication/blob/5bb13591fa600101843906816a416e10b9d58385/api/src/main/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivator.java#L150).

**Comment by brandones** [comment]
I don't understand why this would happen—I don't know anything about DataImporter or... is that metadata mappings? @mogoodrich ? @ibacher ? Any guidance?

**Comment by sherrif10** [comment]
> I don't know anything about DataImporter or... is that metadata mappings?

DataImporter is used when importing and exporting metadata concepts

**Comment by dkayiwa** [comment]
What is the database character set and collation?

**Comment by ibacher** [comment]
@brandones I think, as @dkayiwa alluded to, the problem is likely that the MySQL container is starting up with some character set other than UTF-8. Usually we get the right character set by either [modifying the docker command](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/c47ad85be992c00ecf51b913876d117a56e7e643/docker/docker-compose-refqa.yml#L6) or explicitly controlling the mysql.cnf file (as IIRC PIH EMR does it). Without something like that, the default character encoding is probably `latin1`.

The GitHub Actions documentation doesn't really suggest that there's a good way to change the Docker command, so to ensure the proper encoding, we may need to create a custom MySQL image to be used here.

**Comment by brandones** [comment]
@jayasanka-sack Sorry, just realized I forgot to tag you in this PR...

**Comment by jayasanka-sack** [comment]
@brandones @ibacher 
The following was in the docker file used for 2.x test. I had to remove it since GH service containers don't support it. 
`command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"`

**Comment by jayasanka-sack** [comment]
I ran it again using the https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/docker/docker-compose-refqa.yml file. The result was the same. It sends a 404 for `/ws/rest/v1/session` after starting the server. 

Tried to setup it locally, it was the same. Btw, it crashes all the time. (I'm using an M1 MacBook that might be the issue) @brandones were you able to run it locally?

btw, this message was there when running it on github,

Is it normal? 
```
ERROR - BrokerService.checkSystemUsageLimits(1925) |2021-08-05 14:48:52,958| Temporary Store limit is 51200 mb, whilst the temporary data directory: /usr/local/tomcat/.OpenMRS/activemq-data/localhost/tmp_storage only has 36403 mb of usable space

```

**Comment by ibacher** [comment]
> Is it normal?

It's not great, but it is normal when running OMRS in a Docker container.

> Tried to setup it locally, it was the same. 

So you get the same series of 302s followed by 404s?

> Btw, it crashes all the time. (I'm using an M1 MacBook that might be the issue)

Yeah, I don't think we've tried OMRS extensively on an M1 or even any other ARM-based processor though, theoretically, Java should be platform-agnostic.

**Comment by brandones** [comment]
@jayasanka-sack Were you able to look at the server logs? Is there an error?

> Btw, it crashes all the time. (I'm using an M1 MacBook that might be the issue)

How much RAM do you have? OMRS is a hog. It's most likely just running out of RAM.

**Pull request closed without merging**
