### PR TITLE
Getting Rid of DB.Host property

### PR DESCRIPTION
**Pull request by sherrif10**
https://github.com/openmrs/openmrs-contrib-qaframework/commit/afbed520d89552b1f2d1cfe5a4936ecc88f74b47

### CODE REVIEW

**Comment by sherrif10** [comment]
For platform check we would go with this change.

**Comment by kdaud** [comment]
@sherrif10 did you test out platform tests on this change and they were passing before you merged?

**Comment by sherrif10** [comment]
Yes @kdaud  these were passing locally. i tested them out.

**Comment by kdaud** [comment]
did you test them on github actions?

**Comment by sherrif10** [comment]
> did you test them on github actions?

Yes they also passed on github actions.

**Comment by kdaud** [comment]
how did you test them on github actions?

**Comment by sherrif10** [comment]
Running them on first locally and all workflows were passing and after pushing. they all passed on github actions. thats how i was confident that all was well.

**Comment by kdaud** [comment]
did you try out to run the platform tests manually on github actions and they were passing?

**Comment by sherrif10** [comment]
> did you try out to run the platform tests manually on github actions and they were passing?

Didnt try this out since all workflows passed. Let me do that first.and will get back to you .

**Pull request merged**
