### PR TITLE
adding sonaqube dashboard and sonaqube core into our dashboard

### PR DESCRIPTION
**Pull request by sherrif10**

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 not sure why you're merging your own PRs(pull/223, pull/227, pull/229) without approval. @dkayiwa has never recommended this ideal and has often emphasized not to merge own PR without approval. 

I was still reviewing [pull/229](https://github.com/openmrs/openmrs-contrib-qaframework/pull/229) and you opted to merge it without the reviewers approval and I had more comments regarding where the budge would be placed for better arrangement of QA Dashboard but instead you merged it!

**Comment by sherrif10** [comment]
Ohh yeah sorry about that. It was instead of adding comment. Please feel
free to revert it again. Sorry about that.

**Comment by kdaud** [comment]
@sherrif10 what are you trying to achieve through continuing merging your own unapproved PRs and reverting them? isn't this misuse of your privileges?

 Are you aware of the failing ci builds on the [module](https://ci.openmrs.org/browse/CONTRIB-QA)?

**Comment by kdaud** [comment]
Post-Review: Of what value is it for to have the sonaqube status budge appearing 3-times on the QA-Dashboard?

Screenshot from 2021-11-18 07-48-38

Screenshot from 2021-11-18 07-52-04

**Comment by sherrif10** [comment]
You are viewing the last commit, I reverted that and created a new commit
for you to review

**Comment by kdaud** [comment]
@sherrif10 any response on [this](https://github.com/openmrs/openmrs-contrib-qaframework/pull/232#issuecomment-972523707)?

**Comment by sherrif10** [comment]
I reverted this changes and created a new pull request

**Comment by kdaud** [comment]
> I reverted this changes and created a new pull request

If you reverted them, why are the changes still being reflected in [master](https://github.com/openmrs/openmrs-contrib-qaframework)?

**Comment by sherrif10** [comment]
Check the new pull request I pinged you.

**Comment by kdaud** [comment]
is the ci build fixed?

**Comment by sherrif10** [comment]
Yeap it's fixed

**Comment by kdaud** [comment]
> Yeap it's fixed

Have you checkout the latest build plan at https://ci.openmrs.org/browse/CONTRIB-QA-1108 to verified?
Screenshot from 2021-11-18 08-45-03

**Pull request merged**
