### PR TITLE
Updates to README/QA Dashboard

### PR DESCRIPTION
**Pull request by gracepotma**
@kdaud to help review :)

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@kdaud  @sherrif10  how do  these changes look to you??

**Review by sherrif10 — APPROVED** [review]
LGTM Thanks @gracepotma  cc @dkayiwa

**Comment by kdaud** [comment]
Thanks for the good technical work @gracepotma!

`One comment though:` We do need more of refactoring the `ReadMe file` to make our QA Dashboard look better! 
We need as well to do a little technical change in the respective test workflows to have their status badge have more meaningful readable names that can distinctively difference the `2.x` RefApp tests and `3.x` RefApp tests.

**Comment by sherrif10** [comment]
> espective test workflows to have their status badge have more meaningful readable names that can distinctively difference the

Like which ones which are not making meaningful names.

**Comment by kdaud** [comment]
> We need as well to do a little technical change in the respective test workflows to have their status badge have more meaningful readable names that can distinctively difference the `2.x` RefApp tests and `3.x` RefApp tests.

Will create a ticket to track these changes for future reference for our work. Will ping you on the ticket when ready. cc: @gracepotma

**Comment by kdaud** [comment]
> Like which ones which are not making meaningful names.

My opinion is clear as stated 

> test workflows to have more meaningful readable names that can distinctively difference the 2.x RefApp tests and 3.x RefApp tests

**Comment by sherrif10** [comment]
Which names in refapp 2.x that are not clear, Feel free to show some here

**Comment by kdaud** [comment]
> Which names in refapp 2.x , 3.x that are not clear, Feel free to show some here

`Vitals and Triaging Test` vs `RefApp 2.x Vitals And Triaging Test`

**Comment by kdaud** [comment]
Would love to hear what @gracepotma thinks over the naming of our tests  being the PR author!

**Comment by sherrif10** [comment]
> naming of our RefApp tests

To which RefApp what ?

**Comment by kdaud** [comment]
> To which RefApp name

@sherrif10 did you take a look at this [comment ](https://github.com/openmrs/openmrs-contrib-qaframework/pull/57#issuecomment-892614944) ?

**Pull request closed without merging**
