### PR TITLE
RATEST: Update the read me file for the qaframework module

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud  i think its also part of order if we maintain approval first. One thing why @dkayiwa  removed my privileges is this, so please dont be a victim :smile: like me. Wait we first have final reviews before triggering merge

**Comment by sherrif10** [comment]
Well done @kdaud

**Comment by sherrif10** [comment]
No ticket description , could you add some bit of description

**Comment by dkayiwa** [comment]
> @kdaud i think its also part of order if we maintain approval first. One thing why @dkayiwa removed my privileges is this, so please dont be a victim 😄 like me. otherwise you pay for sins. Wait we first have final reviews before triggering merge

@sherrif10 you seriously have him this time! 😊

**Comment by kdaud** [comment]
> One thing why @dkayiwa removed my privileges is this, so please dont be a victim smile like me. otherwise you pay for sins

Thanks @sherrif10 for sharing your experience. I have learnt a great lesson from your experience. Surely, experience is the best teacher.

**Pull request merged**
