### PR TITLE
Revert "RATEST-327: cypress baseUrl should point to https://dev3.openmrs.org/openmrs/spa"

### PR DESCRIPTION
**Pull request by sherrif10**
Reverts openmrs/openmrs-contrib-qaframework#418

### CODE REVIEW

**Review by jnsereko — APPROVED** [review]
cc @kdaud @dkayiwa look at this so that i can go back to the previous state.
I am working on this logic in https://github.com/openmrs/openmrs-contrib-qaframework/pull/419 
the failure ain't related to this, but https://openmrs.slack.com/archives/CP343JH1R/p1652115592589149 and am to create a separate PR for it.

**Comment by kdaud** [comment]
@jnsereko which server contains the latest changes?

**Comment by jnsereko** [comment]
@kdaud https://dev3.openmrs.org/openmrs/spa has the latest changes but might require changing uuid constants of locations, visits and users so that we  avoid `500 no element with this <uuid>`

It might require some 2 days.  Hopefully i will finish this on Friday

**Comment by kdaud** [comment]
I think we better run the tests on a server containing the latest changes.

> might require changing uuid constants of locations, visits and users so that we avoid 500 no element with this <uuid>

Do you mind to sharing a PR for this?

**Comment by kdaud** [comment]
@sherrif10 @jnsereko is this PR still required?

**Comment by sherrif10** [comment]
I think it's needed because it's pointing to server with latest changes which is dev3.

**Comment by kdaud** [comment]
Which server do we intend to have 3.x tests run on?

**Comment by sherrif10** [comment]
We should use the spa but currently spa is not up to date. So basically I
think dev3 server complises of latest changes

**Comment by kdaud** [comment]
> I think dev3 server complises of latest changes

This is what the tests are using configured at https://github.com/openmrs/openmrs-contrib-qaframework/blob/4a2dda37f492e2487bec7f2c7d612f7de382a1ea/qaframework-bdd-tests/cypress.json#L11

**Pull request closed without merging**
