### PR TITLE
RATEST-293: Add configuration to run platform installation test

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-293)

Description -> Add configuration to run platform installation test

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud  is this used any where in the platform workflows.

**Comment by kdaud** [comment]
I am working around adding a  platform installation test

**Comment by kdaud** [comment]
@dkayiwa we have an existing test for the platform set up wizard though currently not running on ci, I am working around adding config to trigger the [test](https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/TestingInstallSteps.java) to be run on ci. Also looking into how to improve the test to meet the need for set up installation wizard.

Let me know what you think?

**Comment by dkayiwa** [comment]
> Let me know what you think?

Does that test fail if you revert this commit? https://github.com/openmrs/openmrs-core/commit/13fb1d79eac530f63a378c08cd071e8a57d91669

**Comment by kdaud** [comment]
Let me first have it run on ci and test it out on the mentioned use case.

**Comment by sherrif10** [comment]
How is this supposed to be tested against core when there are no rules/steps driving the  platform installation  steps

**Comment by kdaud** [comment]
we have pre-defined rules in the [TestInstallSteps](https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/TestingInstallSteps.java) though they are running ci. Am also looking at how these rules may be modified to suit the set up wizard installation requirements.

**Comment by sherrif10** [comment]
Hey @kdaud  @dkayiwa  , so this is how am understanding this kind of work we wana achieve. If openmrs core gets upgraded, we want to check whether the upgrade went successfully or now right

**Comment by kdaud** [comment]
Thanks @sherrif10 cheeping in on the subject, am not so familiar with platform in general however, @dkayiwa made a comment [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/319#issuecomment-1010979010) concerning the goal of the set up wizard test.

I would love to learn from your experience how these tests can be written to serve the purpose.

**Comment by sherrif10** [comment]
> I would love to learn from your experience how these tests can be written to serve the purpose.

To my understanding may be @dkayiwa can clarify to us more in details to this subject is that, we would love to carryout a framework testing on platform changes or upgrades. Tracking platform upgrades whether plafform have been upgraded from 2.5 to 2.6 version.Then how does this affect the server could be another question that can trigger our mind

Ofcourse we have lots of changes but the ideal point i would think , tracking platfrom upgrade. cc @dkayiwa @kdaud.

**Comment by dkayiwa** [comment]
You seem to be complicating this more than necessary.
Let me put it again. Can you create tests which will fail when this commit is reverted? https://github.com/openmrs/openmrs-core/commit/13fb1d79eac530f63a378c08cd071e8a57d91669

**Comment by sherrif10** [comment]
Thanks @dkayiwa . Its clear now. Thanks for clarification.

**Comment by kdaud** [comment]
@sherrif10 do you mind taking a lead on this and perhaps create ticket(s) to trace what @dkayiwa has clarified?

**Comment by sherrif10** [comment]
Yes am into this @kdaud

**Comment by dkayiwa** [comment]
> do you mind taking a lead on this and perhaps create ticket(s) to trace what @dkayiwa has clarified?

@kdaud i thought you had promised to be done with this by yesterday!

**Comment by kdaud** [comment]
> @kdaud i thought you had promised to be done with this by yesterday!

@dkayiwa as I lookied into the issue and I failed to understand the right requirement clearly and thought it wise to reach out to @sherrif10 via slack so as to collaborate on the solution and perhaps learn from his experience. And that's where the conversation originated and personally would love to learn how this will be achieved as he leads on this.

**Comment by kdaud** [comment]
> @kdaud how would you expect your colleague to understand the requirements more than me who came up with them?

@dkayiwa that tells me I was supposed to reach out to the issue reporter rather. Thanks for correcting me on this and will do it the right way next time.

**Comment by dkayiwa** [comment]
@kdaud does this mean you have given up on it and handed it over to @sherrif10?

**Comment by sherrif10** [comment]
Hello @dkayiwa  hope we should test platform core 2.5.1

**Comment by kdaud** [comment]
> @kdaud does this mean you have given up on it and handed it over to @sherrif10?


@dkayiwa I am willing to learn from him in case is able to push it to the finishing line.

**Comment by dkayiwa** [comment]
> in case is able to push it to the finishing line.

Are you?

**Comment by sherrif10** [comment]
> > in case is able to push it to the finishing line.
> 
> @sherrif10 are you?

ohh Yes @dkayiwa . Am working on it. the first thing is to first understand what happens when that code is removed/added. then i can figure out how the test scripts would look like.

**Comment by dkayiwa** [comment]
@sherrif10 when are you planning to have the test ready?

**Comment by sherrif10** [comment]
Probably by tomorrow morning. the test should be ready.

**Comment by dkayiwa** [comment]
> Probably by tomorrow morning. the test should be ready.

That will be awesome! You are de man!!! 👍

**Comment by sherrif10** [comment]
Hey @dkayiwa is it possible to run a docker image  with a specific platform version.

**Comment by dkayiwa** [comment]
> is it possible to run a docker image with a specific platform version

I have never done that.

**Comment by sherrif10** [comment]
@dkayiwa  it could be something we could investigate .it could be another option of running instances of platform ,for docker devs 🙂

**Comment by dkayiwa** [comment]
> it could be something we could investigate

Feel free to investigate anything in your spare time. 😊

**Comment by sherrif10** [comment]
Finally reproduced it locally.

**Comment by sherrif10** [comment]
Hey @dkayiwa . so have been looking into this following the convention of other workflows like core upgrade. and it seemed to me like the whole idea behind the scene gets executed on commandline then we check the out

**Comment by dkayiwa** [comment]
@sherrif10 did you see the ones that @k-joseph did?

**Comment by sherrif10** [comment]
> @sherrif10 did you see the ones that @k-joseph did?

Yes i saw it but it was catering for only upgrade and it seems it wasn't complete.it confused me somehow

**Comment by dkayiwa** [comment]
@sherrif10 so all we need are browser tests for that page to catch ui changes resulting from that commit.

**Comment by sherrif10** [comment]
> @sherrif10 so all we need are browser tests for that page to catch ui changes resulting from that commit.

Thanks @dkayiwa  . It makes sense now to me. Let me see how best i can come up with that together.

**Comment by sherrif10** [comment]
Hello @kdaud  will be working on this for today.

**Comment by sherrif10** [comment]
plat we testing out this page that is brought about the commit .

**Comment by dkayiwa** [comment]
> plat we testing out this page that is brought about the commit .

This is not the screen am talking about. The one we are dealing with happens to be the update wizard screen which shows up when you upgrade the platform from a lower to a newer version.

**Comment by sherrif10** [comment]
Thnks @dkayiwa . I get it home.

**Comment by kdaud** [comment]
have done a use case on upgrade wizard from a lower platform version to the newest and got up this page during the process
Screenshot from 2022-02-07 20-15-26

@dkayiwa let me know if am on the right track!

**Comment by kdaud** [comment]
Not sure why git auto closed the pr on an attempt of updating it.

**Comment by dkayiwa** [comment]
@kdaud can you also share a screenshot of what the exact same page should look like with the changes in that commit?

**Comment by kdaud** [comment]
> @kdaud can you also share a screenshot of what the exact same page should look like with the changes in that commit?

Screenshot from 2022-02-08 12-51-51

**Comment by kdaud** [comment]
Have added `pull/349` that adds a browser test for the page to catch ui changes resulting from the changes in that commit.

**Comment by dkayiwa** [comment]
> > @kdaud can you also share a screenshot of what the exact same page should look like with the changes in that commit?
> 
> Screenshot from 2022-02-08 12-51-51

This is exactly what i expected to see 👍

**Comment by kdaud** [comment]
Have added pull/349 that adds a browser test for the page to catch ui changes resulting from the changes in that commit.

**Comment by sherrif10** [comment]
@kdaud  this is good progress. So that means am out on this ticket. Leaving this for you to proceed. And concentrate on other things.

**Comment by kdaud** [comment]
@sherrif10 as of now all our platform tests are failing since github action was switched to run on qa server, so I propose we switch the github action to run on the previous instance so as to be able to test out the platform test have added in pull/349. 
Any objection?

**Comment by sherrif10** [comment]
Do you mind commiting that pull request. I didn't want to revert it because there are changes with in that pr. Feel free to revert it and we can see the build plans of platform.remember to watch all reports workflows.

**Pull request closed without merging**
