### PR TITLE
OCLOMRS-989:Create a feature file ready for automated test

### PR DESCRIPTION
**Pull request by jwnasambu**
Issue worked on:
[Create a feature file ready for automated test](https://issues.openmrs.org/browse/OCLOMRS-989)

Changes made:
I created feature files ready for automated testing.

### CODE REVIEW

**Comment by kdaud** [comment]
Add feature title for each file. For example for the feature file located at `src/test/resources/features/ocl-client/01-module/modules.feature ` the title can be `Feature: Modules Management`

**Comment by kdaud** [comment]
This is a good start @jwnasambu and so promising. Catch up my comment above and update the PR

**Comment by jwnasambu** [comment]
@kdaud Thanks for the review am gonna fix it.

**Comment by jwnasambu** [comment]
@kdaud Am supposed to channel this work on the right repo. I will tag you when am done. 

Thanks

**Comment by kdaud** [comment]
Based on this discussion [here](https://github.com/openmrs/openmrs-ocl-client/pull/702#issuecomment-857684172), there might be a need to close this PR. cc: @jwamalwa

**Comment by ibacher** [comment]
Closing this as we're keeping the ODM tests with the ODM code.

**Pull request closed without merging**
