### PR TITLE
RATEST-190: Refactoring clinical visit test and vitals& triaging test configurations to activate their status badges

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-190)
Description -> Activate clinical visit test and vitals& triaging test status badge

### CODE REVIEW

**Comment by sherrif10** [comment]
Thanks @kdaud , How about refactoring clinical visit test and vitals &triaging test, instead of activate clinical visit test

**Review by sherrif10 — APPROVED** [review]
LGTM @kdaud  , just some minor additional of making the title little more readable than the changes

**Comment by kdaud** [comment]
Waiting for any recommendation ! 
cc: @sherrif10

**Comment by kdaud** [comment]
> just some minor additional of making the title little more readable than the changes

> How about renaming the ticket title to refactoring clinical visit test and vitals &triaging test, instead of activate clinical visit test

The changes are activating status badge for Clinical Visit test  and Vitals & Triaiging test on QA Dashboard that is why i labelled the title as "`RATEST-190: Activate clinical visit test and vitals & triaging test status badge`"

**Comment by sherrif10** [comment]
> The changes are activating status badge for Clinical Visit test and Vitals & Triaiging test on QA Dashboard that is why I labelled the title as "`RATEST-190: Activate clinical visit test and vitals & triaging test status badge`"

But you are refactoring the code, Activating means something different from the changes you have committed

**Comment by kdaud** [comment]
> But you are refactoring the code, Activating means something different from the changes you have committed

What commit title would you suggest then ?

**Comment by sherrif10** [comment]
> refactoring clinical visit test and vitals &triaging test,

This would bring it out much more clear

**Comment by kdaud** [comment]
cc: @dkayiwa

**Comment by sherrif10** [comment]
Thanks @kdaud

**Pull request merged**
