### PR TITLE
RATEST-258: Get rid of duplicated files within the qaframework module

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-258)

Description -> Follow up commit for migrating selenium legacy tests into qaframework repo

### CODE REVIEW

**Comment by kdaud** [comment]
For one reason one or two reason, AddUserTest, AddVisitTypeTest, and DeleteVisitTypeTest have been ignored not run simply because have tested them and they are failing within qaframework repo though they are passing in distro-referenceapplication module. 

Most likely the issue may be as a result of libraries they are consuming that may not be supported within qaframework. However, as the the stream of work for coveting legacy tests into BDD these three tests will be fixed.

**Comment by dkayiwa** [comment]
Why do we ignore instead of fixing them? And why only them but not others?

**Comment by kdaud** [comment]
> And why only them but not others?

No so certain !

> Why do we ignore instead of fixing them

These ignored tests need time to be investigated and since these commit is more addressing avoiding duplicates, I suggest we let it into master so that our contributors do not get confused with these issue. I am going to log a ticket for them and I will take the initiative for its resolution.

**Comment by dkayiwa** [comment]
@kdaud can you take a second look at this? https://opensource.com/article/18/6/anatomy-perfect-pull-request

**Comment by kdaud** [comment]
> @kdaud can you take a second look at this? https://opensource.com/article/18/6/anatomy-perfect-pull-request

Thanks for the reminder @dkayiwa 

Have done the needful and as well updated the [QA Technical Documentation](https://wiki.openmrs.org/pages/viewpage.action?pageId=235277297)  on steps followed to run these tests locally.

**Comment by dkayiwa** [comment]
@kdaud some merge conflicts.

**Comment by kdaud** [comment]
> @kdaud some merge conflicts.

@dkayiwa have just noticed that updating the branch with master changes introduces back the deleted files. This is is because the PR recently merged was made before the bdd tests were migrated into a sub-module.

I will add the introduced changes as an update to the branch

**Comment by kdaud** [comment]
@dkayiwa conflict resolved.

**Pull request merged**
