### PR TITLE
RATEST-303:Add hamcrest dependency library

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-303

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud  left a quick pr here, this came along working with selenium legacy tests , that we need this dependency

**Comment by kdaud** [comment]
which test is failing as a result of missing the dependency?

**Comment by sherrif10** [comment]
There is no test that is failing but rather, i want to be able to use this libary in one of our code base. checkout how its being used  here https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-legacy-tests/src/test/java/org/openmrs/contrib/qaframework/legacy/AddPastVisitTest.java#L43  probably here https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-legacy-tests/src/test/java/org/openmrs/contrib/qaframework/legacy/AddPastVisitTest.java#L12

**Comment by kdaud** [comment]
is the dependency required for the workflow test your working on?

**Comment by sherrif10** [comment]
Yes absolutely it's part of the work, am working.

**Comment by kdaud** [comment]
Better to add the dependency within the workflow test that needs it since we can not tell here whether it works or not.

**Comment by sherrif10** [comment]
@kdaud  this dependency is needed, i need it to use it in the visit workflow test am working on . As i have shared the links to the tests, its where its being used. i think thats enough to clearly tell us where its used.

**Comment by sherrif10** [comment]
I needed to make things separate to be able to track them collectively. Kindly allow the merge cc @kdaud

**Review by kdaud — APPROVED** [review]
cc: @dkayiwa

**Comment by sherrif10** [comment]
cc @dkayiwa .Looking forward for the merge.

**Comment by dkayiwa** [comment]
Why do we want to add this library?

**Comment by sherrif10** [comment]
This library was supposed to be added in the current pom file of qaframework-bdd-tests.One reason we need it is because , we need to use some of the methods that it comes along with especially here  https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-legacy-tests/src/test/java/org/openmrs/contrib/qaframework/legacy/AddPastVisitTest.java#L43  .then we import it from https://github.com/openmrs/openmrs-contrib-qaframework/blob/master/qaframework-legacy-tests/src/test/java/org/openmrs/contrib/qaframework/legacy/AddPastVisitTest.java#L12.

**Comment by dkayiwa** [comment]
Let us add it there at the time when we actually need it. That way, we avoid falling into the trap of bloating the repository with things which we think we may need in future but when we sometimes may not.

**Comment by sherrif10** [comment]
@dkayiwa  am using it here with in the commeted lines of code https://github.com/openmrs/openmrs-contrib-qaframework/pull/310

**Comment by dkayiwa** [comment]
Commented out lines are as good as do not exist.

**Comment by sherrif10** [comment]
Yes, wanted to add this dependency separately and continue with the ticket. but this library is being used in that class.

**Comment by kdaud** [comment]
@sherrif10 I would go back to my suggestion I made [earlier](https://github.com/openmrs/openmrs-contrib-qaframework/pull/311#issuecomment-1006830636)

**Comment by sherrif10** [comment]
Sure thanks @dkayiwa  @kdaud

**Pull request closed without merging**
