### PR TITLE
Patch the selenium version and geck driver version

### PR DESCRIPTION
**Pull request by sherrif10**
Hey @dkayiwa  @kdaud  i would think us to revert back selenium version and gecko driver such that we can settle things . i remember reports workflow is the one that resulted into such failures. Let me know what you think.

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 following the conversation at [7f1f3b5](https://github.com/openmrs/openmrs-contrib-qaframework/pull/359) we agreed not to downgrade selenium due to the reasons given there. are you suggesting otherwise?

**Comment by sherrif10** [comment]
Thanks @kdaud . Yes am bit convinced that we should downgrade the selenium version back to its current version first . then handle those errors per error.

**Comment by kdaud** [comment]
did you take a close look at the conversation on the commit shared above?

**Comment by sherrif10** [comment]
Thats cool. Lets wait for @dkayiwa  response on that matter.

**Pull request closed without merging**
