### PR TITLE
Proposed update to QA Dashboard

### PR DESCRIPTION
**Pull request by gracepotma**
@kdaud

### CODE REVIEW

**Comment by kdaud** [comment]
Thanks @gracepotma for your continued the technical support to QA!

The commit looks good !.

You made me think of project managers or business type stake holders who may visit our QA Dashboard. I imaged am a project manager of 5 EMRS and have visited the [QA Dashboard](https://github.com/openmrs/openmrs-contrib-qaframework/tree/master) page to figure out whether I can trust the latest Reference Application of OpenMRS and have come to the QA Dashboard to find out how its doing. The board may quit be confusing for 2.X RefApp display especially some one seeing Legacy Tests and New Workflow Tests it actually adds cognitive workloads for the user.  Though we may have few stake holders visiting our Dashboard but I think we need to put them in mind as well not only catering for technical people but Business type stake holders too.

I do not think that we should use Legacy tests and new Workflow tests as our high level of higher key but having a better way as addressed in the commit seems good to me. 

You made me think as well of investigating on to how we can  ensure if the mother card "ALL Firefox Test" is failing the test  then the specific test failing the build should be marked with a badge of red`(failing)` and as well provide a link to cucumber report directly for easy investigation by the technical personnel.

@gracepotma I know we will be improving our QA Dashboard as we progress with the project because good ideas will come along I know. Otherwise your proposed QA Dashboard Display is really ok with me.

Would love to hear from @sherrif10 in respect to the changes before we can have this PR approved to be ready for merging

**Review by sherrif10 — COMMENTED** [review]
This LGTM as well ,since its different from  the commits made here  https://github.com/openmrs/openmrs-contrib-qaframework/pull/60/files. Thanks @gracepotma .

**Review by kdaud — APPROVED** [review]
I and @sherrif10 would merge this commit into  master based on the reviews!
cc: @dkayiwa @ibacher

**Comment by sherrif10** [comment]
Thanks @gracepotma  @kdaud .

**Pull request merged**
