### PR TITLE
RATEST-295:Use logger to add info messages for debugging purposes

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-295

Basically this ticket is going to help us in  debugging purposes Usually logs are many while running qa.yml workflow and perhaps other workflows .Using logger creteria, we want to be able to track the running of different workflows. Adding such loggers help us to clearly understand which workflow runs first than the other one.

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @kdaud Looking forward for the reviews.

**Comment by kdaud** [comment]
have put a comment on the ticket.

**Comment by sherrif10** [comment]
cc @kdaud was my response on the ticket sufficient enough ?

**Comment by kdaud** [comment]
@sherrif10 have seen your comment on the ticket emphasizing debugging, what do you mean by debugging in respect to current qaframework set up?

**Comment by sherrif10** [comment]
Try to compare my logs here https://github.com/openmrs/openmrs-contrib-qaframework/runs/4692865463?check_suite_focus=true  and logs without this module, so what am trying to emphasize is that , adding loggers is another improvement we can add into our code base to help us while debugging our running workflows,  on top of that, we have been using loggers in most of our openMRS code base so i find it more awesome including it as well. This is different from what cucumber does.Note

**Comment by kdaud** [comment]
do you mind sharing an OpenMRS documentation that emphasizes logging?

**Comment by sherrif10** [comment]
checkout https://wiki.openmrs.org/display/docs/OpenMRS+AOP  and feel free to explore more [here](https://github.com/IsantePlus/isanteplus-qaframework)

**Comment by kdaud** [comment]
Thanks @sherrif10 for sharing the documentation. Have skimmed through the documentation and felt worth to throw some comments. 
I am not well acquainted with the current trend in software development in regard to using/not using loggers in test classes. I noticed the shared documentation was last updated almost 10 years ago( 2012-03-19) and have also noticed logging is not being used in some of the openmrs repos.

I am not opposed to your idea and if adding loggers in test class adds value to the module code base then am ok with the changes in this pull request. Otherwise I would like to hear what @dkayiwa has to say over the subject.

**Comment by sherrif10** [comment]
Great , is this worth approving and we wait for @dkayiwa .

**Comment by dkayiwa** [comment]
Has the qa team just run out of work to do for the remaining period? This is not how we use logging in the industry.

**Comment by sherrif10** [comment]
@dkayiwa  Its not like qa has run out of work really, However found this intresting to have it into our code base, i however decided to use logging instead of println statements which also can do the work perfect.

**Comment by sherrif10** [comment]
@dkayiwa  if this is worth diving into, how would we come up with log levels that will suit the core code base then, if not i can close it

**Comment by dkayiwa** [comment]
@sherrif10 in the first place, this needs more work to fit our logging conventions. Going through that, takes both your time and reviewers for work which makes the situation look as if we have run out of priority tickets to invest our qa efforts in.

**Comment by sherrif10** [comment]
Great thanks, Will hold on to it , will resume on it later. Thanks.

**Comment by dkayiwa** [comment]
Can we put this on the agenda of our today's QA call. That is, how do we come up with tickets for the team to work on? Or does everyone just create tickets for whatever they feel like doing, regardless of its value/priority?

**Comment by sherrif10** [comment]
Sure ,we can bring this on the agenda today. For the tickets to work on Usually it have been christine, @kdaud  and myself used to come up with tickets however usually we bring them to you to have final conclusion, whether its worth it or not.

**Comment by dkayiwa** [comment]
@sherrif10 do you mind pointing me to the current pool of tickets that you guys are picking from?

**Comment by sherrif10** [comment]
@dkayiwa  sure. Here they are https://issues.openmrs.org/projects/RATEST/issues/RATEST-298?filter=addedrecently

**Comment by sherrif10** [comment]
Seem we have few tictets but almost the tickets will be working on have no difference from the other one.

**Comment by dkayiwa** [comment]
Can you confirm with Christine and @kdaud about the pool of tickets that the team is supposed to work on?

**Comment by sherrif10** [comment]
We have been working on this together, will meet with them, but
particularly we are handling on migrating all legacy tests into bed approach

**Comment by dkayiwa** [comment]
> bed approach

@sherrif10 what the heck is this?

**Comment by sherrif10** [comment]
My bad, best approach

**Comment by dkayiwa** [comment]
@sherrif10 what are you currently working on?

**Comment by sherrif10** [comment]
Currently am working on migrating selenium tickets. It's just that have not
been well this week. But resuming serious work.

**Pull request closed without merging**
