### PR TITLE
RATEST-242-patch-1: Removing redundant code in the conditions steps definition file

### PR DESCRIPTION
**Pull request by mherman22**
**Description**:
This is a fix following the discussion about the subject on https://github.com/openmrs/openmrs-contrib-qaframework/pull/340

### CODE REVIEW

**Comment by kdaud** [comment]
@mherman22 are all the changes in the commit required?

**Comment by mherman22** [comment]
> @mherman22 are all the changes in the commit required?

i believe so, i have removed the redundant methods from the file. and in the second commit i was correcting the indention in the file

**Review by kdaud — APPROVED** [review]
cc: @sherrif10

**Comment by sherrif10** [comment]
@kdaud are we ignoring the failing report  workflow in this commit.

**Comment by kdaud** [comment]
@sherrif10 is the report test part of the work in this PR?.

**Comment by sherrif10** [comment]
Have you taken a look at my comment on [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/340)

**Comment by kdaud** [comment]
> Have you taken a look at my comment on [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/340)

could you check the link you provided whether it redirects to the comment you are referring to?

**Comment by sherrif10** [comment]
> could you check the link you provided whether it redirects to the comment you are referring to?

Refer to the comments below on the same link.

**Comment by kdaud** [comment]
@mherman22 can we have this commit handle only one thing? ie `Removing redundant code in condition steps definition file`

**Comment by mherman22** [comment]
> @mherman22 can we have this commit handle only one thing? ie `Removing redundant code in condition steps definition file`

@kdaud that is what being handled, i was just updating my branch with the latest changes from upstream

**Comment by kdaud** [comment]
@mherman22 I can see formatting issue(indention) which need to be handled in another commit if desirable. Let this commit handle only one thing.

**Comment by mherman22** [comment]
> @mherman22 I can see formatting issue(indention) which need to be handled in another commit if desirable. Let this commit handle only one thing.

Lemi erectify that. i thought the bad indention was caused by my IDE

**Review by kdaud — APPROVED** [review]

**Pull request merged**
