### PR TITLE
RATEST-281: Fixes the typo in the .yml file for the condition workflow test

### PR DESCRIPTION
**Pull request by Irenyak1**
Ticket ->[ RATEST-281](https://issues.openmrs.org/browse/RATEST-281)
Fixed -> Typo in the naming of the .yml for the condition workflow test.

### CODE REVIEW

**Comment by Irenyak1** [comment]
@kdaud and @sherrif10 , please review this small change when  you find time.

**Comment by kdaud** [comment]
@Irenyak1 did you take a look at the ticket label?

**Comment by Irenyak1** [comment]
> @Irenyak1 did you take a look at the ticket label?

sure @kdaud I did. Was I meant to name it as refapp-2x-patient-condition.yml? I could immediately edit this.

**Comment by kdaud** [comment]
@Irenyak1 did you take a look at the ticket label?

**Comment by Irenyak1** [comment]
> @Irenyak1 did you take a look at the ticket label?

@kdaud is there something I have not captured?

**Comment by kdaud** [comment]
which labels are attached on the ticket?

**Comment by Irenyak1** [comment]
> which labels are attached on the ticket?

@kdaud  QA intro. Those are the labels.

**Comment by mherman22** [comment]
> > which labels are attached on the ticket?
> 
> @kdaud QA intro. Those are the labels.

We could maybe leave the intro tickets for the newbies,  is that the message your putting across @kdaud ?!

**Review by kdaud — APPROVED** [review]

**Comment by kdaud** [comment]
cc: @sherrif10

**Review by sherrif10 — APPROVED** [review]
Thanks @Irenyak1

**Comment by Irenyak1** [comment]
> I agree with @mherman22

@kdaud may my sins be forgiven. :smiley:

**Comment by Irenyak1** [comment]
> Thanks @Irenyak1

@sherrif10  and @kdaud is there still a genuine reason for not merging this into master?

**Pull request merged**
