### PR TITLE
RATEST-150: E2E Search and Registration of New Patient

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-150 cc @ibacher @dkayiwa @kdaud

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @dkayiwa , still we have same issue here https://github.com/openmrs/openmrs-contrib-qaframework/pull/54/checks?check_run_id=3192178653

**Comment by kdaud** [comment]
> still we have same issue here

@sherrif10 as I mentioned [here](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/516#issuecomment-888801773) on this [PR](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/516) did you test locally this workflow before the sister was merged?

**Comment by dkayiwa** [comment]
> in the sister PR

and the brother pr?

**Comment by sherrif10** [comment]
This commit work perfect , All the automations are working as expected locally , the only problem is that github actions and configured ci tracks all the changes being pushed,this commit only breaks after pushing  with the same issue error log.

**Comment by dkayiwa** [comment]
@sherrif10 the error is different from the original one.

**Comment by kdaud** [comment]
> the only problem is that github actions and configured ci tracks all the changes being pushed,this commit only breaks after pushing with the same issue error log.

When the test passes well locally then it should pass on Actions as well. You might need to consider testing locally the workflow on firefox and chrome for both headless true/false instance

**Comment by sherrif10** [comment]
> > the only problem is that github actions and configured ci tracks all the changes being pushed,this commit only breaks after pushing with the same issue error log.
> 
> When the test passes well locally then it should pass on Actions as well. You might need to consider testing locally the workflow on firefox and chrome for both headless true/false instance

So you mean when i say it passes locally i meant it fails locally

**Comment by sherrif10** [comment]
Waiting on the build thanks for reviewing ,its my honor

**Comment by kdaud** [comment]
> So you mean when i say it passes locally i meant it fails locally

@sherrif10 what I meant is to ensure the test workflow is tested on chrome headless false and true, and as well on firefox instance too!

Have had use cases where the test could pass locally  on firefox headless `true` and `false` and as well passes on chrome headless `false` and **fails** with chrome headless `true`. Not until have debugged the test to pass on all instances then ci passes too! Otherwise that is what I meant in particuaar

**Comment by sherrif10** [comment]
> @sherrif10 the error is different from the original one.

Hello @dkayiwa  it still the same error as seen through the logs here   Searching for missing patient(Search And Patient Registration): Expected condition failed: waiting for element to be clickable: By.id: phoneNumberLabel ()

**Comment by kdaud** [comment]
> Expected condition failed: waiting for element to be clickable: By.id: phoneNumberLabel ()

Does this mean when you use `visibility` rather than `clickable` the test pass?

**Comment by sherrif10** [comment]
> s mean when you use `visibilityOfElement` rather than `clickable` the test passes?

Thats what am thinking currently to be the last option since am seeing logs are the returning the same error

**Comment by kdaud** [comment]
> Thats what am thinking currently to be the last option since am seeing logs are the returning the same error

As @dkayiwa mentioned [here](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/516#discussion_r678966369) I think the solution  is neither using `visibilityOfElement` nor `clickable ` but rather looking into why the element is not visible. 

Some pages takes longer to load and the mess might be caused by the loading of the previous page!

**Comment by sherrif10** [comment]
Carrying out a quick test on bamboo, Watching all the builds and failures of this project

**Comment by sherrif10** [comment]
Reverted this

**Pull request merged**
