### PR TITLE
RATEST-264: Fix the clinical visit logic flow in 2.x RefApp test

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-264)

Description -> Fix the clinical visit logic flow in 2.x RefApp test

### CODE REVIEW

**Comment by kdaud** [comment]
> shall we advise him to come up with the something working.

I personally tested the workflow locally and it randomly fails build plans, my recommendation to @Ndacyayisenga-droid is to add the  fix in this PR in his work to have his test pass otherwise there is a snag in the workflow that makes the test fail randomly.

cc: @sherrif10

**Comment by kdaud** [comment]
> With which failures.



> With which failures.

checkout https://github.com/openmrs/openmrs-contrib-qaframework/runs/4018131649?check_suite_focus=true

**Comment by sherrif10** [comment]
@kdaud  is this what it needs for the fix, am seeing .a user fills the Request appointment form  also fails.

**Comment by kdaud** [comment]
the fix I made here is sufficient

**Comment by sherrif10** [comment]
Have you tried to re run the badge and confirm the failure logs

**Comment by kdaud** [comment]
I made a thorough investigation on the workflow and came up with the fix here which should be sufficient . However, If you think its not sufficient feel free to come up with one !

**Comment by sherrif10** [comment]
The idea is to come up with one fix that works all through , i shared that because last night i encountered this failure but i guess its not insufficient if its to do with feature files according to the logs.

**Comment by kdaud** [comment]
@Ndacyayisenga-droid is been blocked while working on [RATEST-225](https://issues.openmrs.org/browse/RATEST-225) and I took time to investigate the workflow and the fix here is sufficient enough. From experience some tests can fail randomly and their logs can not tell the exact cause until investigated and find out where things are being messed up. Here is a sample of a test([RATEST-75](https://issues.openmrs.org/browse/RATEST-75)) whose logs could not point to the exact issue until it was investigated and fixed.

**Comment by sherrif10** [comment]
> Have you tried to re run the badge and confirm the failure logs. Probably this might be of help https://github.com/openmrs/openmrs-contrib-qaframework/runs/4064387667?check_suite_focus=true

@kdaud  have you tried re running the clinical build to see the error log

**Comment by kdaud** [comment]
> have you tried re running the clinical build to see the error log

@sherrif10 I took over hours when investigating  the workflow but you seem not satisfied with what have mentioned above, come up with a fix that you feel its sufficient.

**Comment by sherrif10** [comment]
@kdaud  feel free to do the needful, we shall  fix any other error when it shows up.

**Review by sherrif10 — APPROVED** [review]
LGTM

**Comment by kdaud** [comment]
Am making  a follow up on the build failures and soon to rise a PR that will fix the plan. cc: @sherrif10

**Comment by sherrif10** [comment]
@kdaud  this is the error i was talking about before merge https://github.com/openmrs/openmrs-contrib-qaframework/runs/4065332157?check_suite_focus=true  . Thanks for following up on it

**Comment by kdaud** [comment]
@sherrif10 checkout the report at https://talk.openmrs.org/t/automated-test-for-booking-an-appointment-catches-a-bug/34993

**Comment by sherrif10** [comment]
@kdaud  lets resolve clinical issue and have other guys merged, this is blocking me on report workflow. Did this resolve the bug

**Pull request merged**
