### PR TITLE
Set System property to whitelistedIps

### PR DESCRIPTION
**Pull request by sherrif10**
cc @kdaud  Trial fix to the ci failing to run chrome successfully on remote machine.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@sherrif10 which problem are you trying to solve with this merge?

**Comment by sherrif10** [comment]
@dkayiwa  Trying to solve failures on the Bamboo as reflected in the logs here https://ci.openmrs.org/download/CONTRIB-QA-FRAMEWORK/build_logs/CONTRIB-QA-FRAMEWORK-1659.log.

**Comment by dkayiwa** [comment]
Do you revert if it does not work? Because i saw you made another commit yesterday which also did not fix the failure.

**Comment by sherrif10** [comment]
Sure will revert it if it doesnt resolve the issue.

**Comment by dkayiwa** [comment]
How about the one of yesterday?

**Comment by sherrif10** [comment]
Yeap Actually am going to revert both of them right now.

**Pull request merged**
