### PR TITLE
O3-1053: RefApp 3.x Login E2E test to run in a dockerized environment

### PR DESCRIPTION
**Pull request by pasindur99**
### Purpose
The purpose of this PR is to fix [O3-1053](https://issues.openmrs.org/browse/O3-1053).

### Approach
Run 3.X login E2E test in a dockerized environment.

### CODE REVIEW

**Comment by sherrif10** [comment]
Hey @pasindur99   any progress on this ticket.

**Comment by pasindur99** [comment]
Will update the progress of the ticket soon @sherrif10 .
Could you please review the pr @jayasanka-sack .

**Comment by pasindur99** [comment]
Sure @jayasanka-sack . Are there any errors that you could figure out in the changed workflow file?

**Comment by jayasanka-sack** [comment]
It doesn't seem an error of the workflow file, but something within the test. Is it passing locally?

**Comment by pasindur99** [comment]
No. The test is failing locally, we are in the phase of fixing those issues.

**Comment by jayasanka-sack** [comment]
The setup isn't viable to address current challenges. We should work on a different approach. Therefore, closing the PR.

Thanks @pasindur99 !

**Pull request closed without merging**
