### PR TITLE
RATEST-347: Allow remote connections to Chrome from any origin

### PR DESCRIPTION
**Pull request by Muta-Jonathan**
## Summary

For some OS.... While Running e2e tests ..this is thrown https://pastebin.com/L8QbmwB6 

## Worked On Issue

👓  https://issues.openmrs.org/browse/RATEST-347 

cc @sherrif10 @jayasanka-sack @Piumal1999 @kdaud

### CODE REVIEW

**Comment by Muta-Jonathan** [comment]
> @Muta-Jonathan, how can the issue be reproduced?

Basically have tried it on my pc running on Ubuntu_20.04

**Comment by kdaud** [comment]
Does it happen on a specific test?

**Comment by Muta-Jonathan** [comment]
> Does it happen on a specific test?

not really @kdaud  - here is a video to show the error 

---

https://github.com/openmrs/openmrs-contrib-qaframework/assets/86114366/2ced9aa3-b27f-45f3-8645-399516b2f5ff

**Comment by kdaud** [comment]
Which server are you using to run the test?

**Comment by Muta-Jonathan** [comment]
> Which server are you using to run the test?

tried both QA server and Local server

**Comment by kdaud** [comment]
Are you able to reproduce the issue on any of the tests via [github actions](https://github.com/openmrs/openmrs-contrib-qaframework/actions)?

**Comment by Muta-Jonathan** [comment]
> Are you able to reproduce the issue on any of the tests via [github actions](https://github.com/openmrs/openmrs-contrib-qaframework/actions)?

not really @kdaud but according to [this address](https://stackoverflow.com/questions/75678572/java-io-ioexception-invalid-status-code-403-text-forbidden) it shows that this error basically happens due to denial of local permission access 

take a look [here 403 Forbidden Error](https://stackoverflow.com/questions/75718696/i-am-getting-error-while-launching-chrome-browser-using-selenium-java-io-ioexcep) 
---
`Typically, ChromeOptions used for a headless run. However, the new chrome version 111 is not compatible with the latest Selenium version even for 4.8, so for the time being this is an alternative solution.`

**Comment by kdaud** [comment]
Are all the tests failing locally with chrome?

**Comment by Muta-Jonathan** [comment]
> Are all the tests failing locally with chrome?

yes @kdaud all fail locally

**Comment by kdaud** [comment]
What happens when you spin the tests on firefox engine?

**Comment by Muta-Jonathan** [comment]
> What happens when you spin the tests on firefox engine?

@kdaud it runs successfully .... without even changes .....because basically this error is caused due to chrome permissions...

---
Screenshot from 2023-05-12 10-08-58

**Comment by kdaud** [comment]
Could you share the chrome browser version running on your machine and the chrome driver version installed  locally at [this](https://github.com/openmrs/openmrs-contrib-qaframework/tree/master/qaframework-bdd-tests/src/test/resources/chromedriver/linux) directory?

**Comment by Muta-Jonathan** [comment]
> Could you share the chrome browser version running on your machine and the chrome driver version installed locally at [this](https://github.com/openmrs/openmrs-contrib-qaframework/tree/master/qaframework-bdd-tests/src/test/resources/chromedriver/linux) directory?

Am using `Chrome Version 112.0.5615.165 (Official Build) (64-bit)` and its the driver i downloaded from [here](https://chromedriver.storage.googleapis.com/index.html?path=112.0.5615.49/)

**Comment by kdaud** [comment]
The issue is most likely due to incompatibility between the chrome browser and the driver being used to run the test( **.165** vs **.49**. Note → The driver's version(.49) is slightly higher than that of the browser suggesting that it contains some components which .165 version can not resolve.
 
Try to down grade the chrome driver to v [112.0.5615.28/](https://chromedriver.storage.googleapis.com/index.html?path=112.0.5615.28/) or v[111.0.5563.64/](https://chromedriver.storage.googleapis.com/index.html?path=111.0.5563.64/)

**Comment by kdaud** [comment]
@Muta-Jonathan any feedback on the comment above :point_up: ?

**Comment by kdaud** [comment]
@Muta-Jonathan is this PR still relevant?

**Comment by Muta-Jonathan** [comment]
@kdaud I think we havent got any issue regarding this again in a couple of months ...... 
Maybe @sherrif10 & @dkayiwa what do you think should we close this off or merge it

**Comment by dkayiwa** [comment]
If you haven't got any issue, you can close.

**Pull request closed without merging**
