### PR TITLE
Ratest 269 : Deletion of spaces in the Conditions feature file

### PR DESCRIPTION
**Pull request by mherman22**
**Ticket ID**
https://issues.openmrs.org/browse/RATEST-269

**Description**
The purpose of this pull request is to delete the spaces withing the scenarios in the conditions feature file

**Reference**
https://github.com/openmrs/openmrs-contrib-qaframework/pull/174

**Things done to that effect**
1. i have deleted the spaces in each of the scenarios

cc : @kdaud

### CODE REVIEW

**Comment by mherman22** [comment]
why do i have all commits from https://github.com/openmrs/openmrs-contrib-qaframework/pull/174 here

**Comment by kdaud** [comment]
> why do i have all commits from #174 here

its because you did not reset your branch to be equivalent to master before introducing your changes!

**Comment by mherman22** [comment]
ooh alright , am deleting this branch in the meantime

**Comment by kdaud** [comment]
> am deleting this branch in the meantime

@mherman22 so are you creating a new PR?

**Comment by mherman22** [comment]
> > am deleting this branch in the meantime
> 
> @mherman22 so are you creating a new PR?

yes i am

**Comment by mherman22** [comment]
> its because you checkout a new branch off RATEST-242 and did not reset your branch to be equivalent to master before introducing your changes
 when i reset my branch  dont i lose my changes? Then how am gonna work on the conditions feature file?

**Comment by kdaud** [comment]
@mherman22 create a new branch off master and do your changes that meet the ticket requirement!

**Pull request closed without merging**
