### PR TITLE
Add path to segregate open concept lab test on PRs

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud this is disabling the workflow.

**Comment by kdaud** [comment]
I have not got your point sir, do you mind phrasing it differently?

**Comment by kdaud** [comment]
Which ticket is not getting triggered?

**Comment by sherrif10** [comment]
@ is this ticket have any actions running?

**Comment by sherrif10** [comment]
This pull is already segregated, did uu watch what happened in this pull request. https://github.com/openmrs/openmrs-contrib-qaframework/pull/393 before it got merged.

**Comment by kdaud** [comment]
@sherrif10 are you sure the test won't run when a change is done in 3.x tests?

**Comment by sherrif10** [comment]
Why is it not running with your changes

**Comment by kdaud** [comment]
Because it's now segregated !

**Review by sherrif10 — APPROVED** [review]
Thanks . Let's see how it will load. However this initially ran as expected.

**Pull request merged**
