### PR TITLE
Rename  Status badge   for find patient Workflow

### PR DESCRIPTION
**Pull request by sherrif10**
https://github.com/openmrs/openmrs-contrib-qaframework/pull/127
 Update readme file for find Patient Badge

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @dkayiwa  here is the quick fix for updating the badge

**Comment by kdaud** [comment]
Worth adding a brief commit description. Am tempted to think of a ticket to track this change But am convinced its not worth creating a ticket since its a minor change.

**Comment by sherrif10** [comment]
I think adding a ticket where all the changes reside also adds up all

**Comment by dkayiwa** [comment]
Is this updating the readme? Or simply a file rename?

**Comment by sherrif10** [comment]
Resolved Thanks

**Comment by sherrif10** [comment]
> Resolved Thanks
Hello @dkayiwa, is this worth it

**Comment by dkayiwa** [comment]
True dat @sherrif10 👍

**Comment by sherrif10** [comment]
Thanks @dkayiwa

**Pull request merged**
