### PR TITLE
RATEST-216:Remove Refapp.2.x from Refapp.3.x cypress directory

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-216  cc @jayasanka-sack  @kdaud

### CODE REVIEW

**Comment by sherrif10** [comment]
This doesnot teach them anything in terms of technical part , its better we leave some tickets that will little  challenge them for them to learn more.

**Comment by sherrif10** [comment]
Am merging this ,since its straight to get into master.

**Comment by kdaud** [comment]
@sherrif10 what about those starting off with their open source development ? Don't you think such a ticket

**Comment by kdaud** [comment]
@sherrif10  before you merged did you see my comment [above ](https://github.com/openmrs/openmrs-contrib-qaframework/pull/105#issuecomment-910658326) ?

BTW @dkayiwa advised us not to merge commits before its approved! @dkayiwa can give advise again to us but I remember him recommending us not to merge commits before approval !

cc: @dkayiwa

**Comment by dkayiwa** [comment]
Very good point @kdaud 👍

**Pull request merged**
