### PR TITLE
RATEST-258:Migrate All The Tests From Distro Into qa Framework

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-258

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 do you have time to finish up this guy because we need selenium legacy tests to be migrated soon and then have @dkayiwa  merge the PRs that delete the origins? 

Or some one else can take it up?

**Comment by sherrif10** [comment]
Am resolving this issue at the moment.Hopefully to come up with resolution.

**Comment by kdaud** [comment]
@sherrif10 is there any way I can support you to have this PR done?

**Comment by sherrif10** [comment]
@kdaud  Give me some ample time please, i hope this is not blocking anyone to proceed. Am working on this ticket, i probably promise to ping you for support.Thanks a lot.

**Pull request closed without merging**
