### PR TITLE
RATEST-349: Run 2.x E2E tests on chrome and firefox via github actions

### PR DESCRIPTION
**Pull request by anjula-sack**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] I have tested the changes locally and verified that they work as intended.
- [ ] I have added comments to my code where necessary to help others understand my changes.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary

For a while RefApp 2.x e2e tests have been running on the Firefox browser in GitHub actions. In this PR the all the tests are being updated to run on chrome as well. This was achieved by updating the github actions workflows.

## Screenshots

*None.*

## Related Issue

https://issues.openmrs.org/browse/RATEST-349

## Other

*None.*

### CODE REVIEW

**Comment by kdaud** [comment]
Thanks @anjula-sack for pulling this up. Could you help me understand how this work?

**Comment by kdaud** [comment]
So which browser is being used by the tests as per this commit?

**Comment by anjula-sack** [comment]
> So which browser is being used by the tests as per this commit?

Both of them. Check the tests, you can see every test has been ran twice. One with chrome and the other with firefox.

**Comment by kdaud** [comment]
Have skimmed through the logs and noticed all the two jobs are running on firefox browser.

https://github.com/openmrs/openmrs-contrib-qaframework/actions/runs/5076943535/jobs/9119634346?pr=485#step:7:11615

https://github.com/openmrs/openmrs-contrib-qaframework/actions/runs/5076943535/jobs/9119634430?pr=485#step:7:11636

Could you take a look at the logs to find out why this is happening so? What would happen when you switch browser order and begin with chrome?.

`    strategy:
      matrix:
        browser:
          - chrome
          - -firefox`

**Review by Piumal1999 — COMMENTED** [review]
Good job @anjula-sack . I added some comments

**Comment by anjula-sack** [comment]
@kdaud Check now. It's running on both now. I had to update the properties.

**Review by kdaud — APPROVED** [review]
Great work! 
Thanks @anjula-sack

**Comment by kdaud** [comment]
@anjula-sack, revert the changes that were made in the platform ui tests.

**Comment by anjula-sack** [comment]
> @anjula-sack, revert the changes that were made in the platform ui tests.

Didn't get you?

**Comment by kdaud** [comment]
The platform ui tests should be excluded from the changes and that's why they are [failing](https://github.com/openmrs/openmrs-contrib-qaframework/actions/runs/5107760574/jobs/9180951154) plans in master, look out for the .yaml files starting with `platform-..yaml` and revert their respective changes.

**Pull request merged**
