### PR TITLE
RATEST-244:Update chrome driver to  94.0.4606.71

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-244

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @kdaud

**Comment by kdaud** [comment]
@sherrif10 what is the motive for updating the chrome driver version?

**Comment by sherrif10** [comment]
Hello @kdaud  waiting for approval as we have been doing it.

**Comment by kdaud** [comment]
@sherrif10 was it intentional to edit the reviewer's comment [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/140#issuecomment-934058063)?

**Comment by sherrif10** [comment]
> was it intentional to edit the reviewer's comment [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/140#issuecomment-934058063)?

uhm the intension is to increase chrome driver version, am not sure if you have been clearly seeing the current version behaviours, but ideally the intension is to have chrome driver run on stable version as 89.04 became duplicate

**Comment by kdaud** [comment]
@sherrif10 its not a good practice to edit a reviewer comment(s) regardless of having this privilege. The edited review losses meaning. Now the reviewer's comment on this PR has been edited to something different and makes reviewing your PR quit hard ! 
Screenshot from 2021-10-05 08-55-03

@dkayiwa do we have a documentation that talks about this?

**Comment by sherrif10** [comment]
Sorry that was a mistake.

**Review by mherman22 — COMMENTED** [review]
great work, we needed this for compatibility

**Comment by sherrif10** [comment]
Hey @kdaud  still waiting for approval

**Comment by kdaud** [comment]
> am not sure if you have been clearly seeing the current version behaviours

Not really !

@sherrif10 what was the behavior all about?

**Comment by sherrif10** [comment]
> what was the behavior all about?

Chrome is no longer supported try to run any single test on chrome version 89.0 and below, you will encounter that behavior that chrome version is no longer supported hence throwing errors

**Comment by mozzy11** [comment]
>@sherrif10 its not a good practice to edit reviewers' comment(s) regardless of having a privilege. The reviewer's comment losses meaning. Use case: The reviewer's comment on this PR has been edited to something different and makes reviewing your PR quite hard !

:face_with_thermometer:

**Comment by kdaud** [comment]
> Chrome is no longer supported

Am skeptical about this! @sherrif10 have you read this from a trusted website and are you able to refer to it?

**Comment by sherrif10** [comment]
> Am skeptical about this! @sherrif10 have you read this from a trusted website and are you able to refer to it?

Interesting, Have you tried to simulate any single test on chrome version 89.0 an below?

**Comment by kdaud** [comment]
From my end tests are passing locally with the chrome version 89.0.4389.23 am running.

@sherrif10 is upgrading the chrome driver catering for local simulation or CI? And is the current chrome version failing any test with CI?

**Comment by sherrif10** [comment]
> upgrading the chrome driver catering for local simulation or CI? And is the current version failing any test with CI?

its catering for both  local   and ci  simulations

**Comment by sherrif10** [comment]
> From my end tests are passing locally with the chrome version 89.0.4389.23 am running.

Are you sure about this ?

**Comment by mozzy11** [comment]
Anyways , CI runners are continuously updated , so they always work with the latest versions of available public software.
in this case the GitHub Actions runners currently run with the latest version of chrome which is 94 .
So we have to update the selenium chrome driver to the latest ,so that its compatible with the chrome version supported by the github runner

**Comment by mozzy11** [comment]
>  From my end tests are passing locally with the chrome version 89.0.4389.23 am running.
Thats true because  your local machine runs with that version of chrome.

**Comment by sherrif10** [comment]
Thanks @mozzy11  for clarification.

**Comment by kdaud** [comment]
I'm not opposed to the idea of upgrading the driver!

AFAICT its quite hard to cater for every one when it comes to local simulation due to different driver versions contributors are using on their machines. For local simulation one has to ensure chrome/firefox driver version is matching the installed browser running on the machine and this is documented in our QA technical [wiki](https://wiki.openmrs.org/pages/viewpage.action?pageId=235277297)!



> in this case the GitHub Actions runners currently run with the latest version of chrome which is 94

Github Actions build plans for the automated tests are spinning from firefox not chrome. Chrome is being used by Bamboo build plans.

I remember almost two [months ago,](https://github.com/openmrs/openmrs-contrib-qaframework/pull/66) an upgrade to chrome driver was made to the latest version by that time But the upgrade turned resulted into failing Bamboo build plan.

**Comment by sherrif10** [comment]
We need this version to be on the latest version of chrome as clearly clarified above  by @mozzy11 , You seem to have reported 91 version not 94 may be it wasn't compatible with the system.

**Comment by kdaud** [comment]
> You seem to have reported 91 version not 94 may be it wasn't compatible with the system.

@sherrif10 have may take a second look at;

>  I remember almost two [months ago,](https://github.com/openmrs/openmrs-contrib-qaframework/pull/66) an upgrade to chrome driver was made to the latest version by that time But the upgrade turned into failing Bamboo build plans.

**Comment by sherrif10** [comment]
Let's try it out will cater for breakages incase anything breaks, its been quite some time without upgrading the chrome driver. Thanks again @kdaud

**Review by kdaud — APPROVED** [review]
> Let's try it out will cater for breakages incase anything breaks, its been quite some time without upgrading the chrome driver

Sounds fair enough. :)

**Comment by sherrif10** [comment]
cc @dkayiwa

**Comment by kdaud** [comment]
@sherrif10 feel free to merge the PR and keep an eye on the build plan!

**Comment by dkayiwa** [comment]
Just in case you find this helpful: https://wiki.openmrs.org/display/docs/Code+of+Conduct

**Comment by kdaud** [comment]
While investigating why [QA Framework](https://ci.openmrs.org/browse/CONTRIB-QA) is failing, have noticed the chrome driver version that was upgraded in this commit for Bamboo to use can not be instantiated during the build plan and all the existing workflow tests are [failing](https://reports.cucumber.io/reports/a1f2d510-2367-4469-b2a1-2ab9a18445c4). 

We may need to revert this commit for Bamboo to spin from the previous version as I investigate further!
cc: @sherrif10  @dkayiwa

**Comment by kdaud** [comment]
Before the chrome upgrade, some tests were passing and others were failing randomly. But of now all the tests are failing. 
[Two months ago](https://github.com/openmrs/openmrs-contrib-qaframework/pull/66) we had an upgrade in the chrome driver and the same behavior that is happening now occurred, and we had to revert the the commit. My take for now is to have the upgrade in this commit reverted to have the tests back to life. Will get time to investigate why an upgrade in chrome driver fails the test and after resolving the problem, then we will have the driver safely upgraded.

cc: @sherrif10  @dkayiwa

**Comment by kdaud** [comment]
> Here we go: https://ci.openmrs.org/browse/CONTRIB-QA-FRAMEWORK-903

Have quickly skimmed through the logs and now our tests are passing as per cucumber report at https://reports.cucumber.io/reports/d194dd19-3c1e-4f0c-9007-671ff210102b . Am taking a further investigation on why the build plan shows red when all the tests are passing!

**Comment by dkayiwa** [comment]
Restored here: https://github.com/openmrs/openmrs-contrib-qaframework/commit/9d7a258aec6c8106f76a604d3cb61440415dad6f

**Comment by kdaud** [comment]
> now we have to debug a single failing test

@mozzy11 I personally notice an upgrade in the chrome driver is failing all the workflow tests within the module via Bamboo build plan as per the cucumber report at https://reports.cucumber.io/reports/5ed6afaa-5ebc-4e89-b1f9-679ed3406f35 for the latest build plan.

And now that @dkayiwa has restored the upgrade, any one can investigate.

**Comment by sherrif10** [comment]
sure thnks

**Comment by mozzy11** [comment]
you were supposed to upgrade form 89.0.4389.23 to 90

**Pull request merged**
