### PR TITLE
RATEST-194: Create a feature file For Forms Management

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-194

### CODE REVIEW

**Comment by kdaud** [comment]
Any reason for creating feature file for forms ?

**Comment by sherrif10** [comment]
Sure the ideal reason would be automating this form in a new workflow, Any suggestion that would deny this test to be worked upon.

**Comment by kdaud** [comment]
> Any suggestion that would deny this test to be worked upon.

If the test was not covered by the legacy selenium tests then its worth to be worked !

**Comment by kdaud** [comment]
> Any suggestion that would deny this test to be worked upon.

If the test was not covered by the legacy selenium tests then its worth to be worked !

**Comment by sherrif10** [comment]
Wont do since it was covered in the old test framework

**Pull request closed without merging**
