### PR TITLE
Use chrome version 90.0.4430.24 to run uitests in bamboo

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by sherrif10** [comment]
@kdaud Does this fix the bamboo.

**Comment by kdaud** [comment]
It's an attempt to fixing ci, the build plan turned out red.

**Comment by kdaud** [comment]
The issue is now resolved and the ui tests are able to run in ci.

**Comment by dkayiwa** [comment]
> The issue is now resolved and the ui tests are able to run in ci.

Are you sure?

**Comment by dkayiwa** [comment]
The link you shared for the logs shows a build failure.

**Comment by kdaud** [comment]
Previously none of the tests would login into the server as a result of incompatibility of the driver, that is now sorted out.

**Comment by dkayiwa** [comment]
> @kdaud Does this fix the bamboo.

@sherrif10's original question still stands.

**Comment by kdaud** [comment]
Taking a close look at the current [logs](https://ci.openmrs.org/browse/CONTRIB-QA-FRAMEWORK-1763/log) shows a few tests just breaking randomly and other the rest passing as per the [cucumber report](https://reports.cucumber.io/reports/08e60b06-9be8-48de-a7d1-5a9f52041ad3)

Possibly the current issue is coming from the bamboo side(configs) that are making the plans to misbehave.

**Pull request merged**
