### PR TITLE
O3-2123: Remove the bamboo build status icons

### PR DESCRIPTION
**Pull request by Muta-Jonathan**
## Summary
- Removed bamboo icon status badges

## Related Issue
🙄  https://issues.openmrs.org/browse/O3-2123

## Screenshots
Screenshot from 2023-05-18 17-38-52

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]
Thank you! @Muta-Jonathan

**Comment by sherrif10** [comment]
Any reason why we are removing bamboo status?

**Comment by Muta-Jonathan** [comment]
> Any reason why we are removing bamboo status?

yes @sherrif10 follow here https://talk.openmrs.org/t/bamboo-build-status-icons-are-not-loading/39528/12

**Comment by sherrif10** [comment]
Alright thanks cc @jayasanka-sack @kdaud

**Comment by anjula-sack** [comment]
Here's the issue https://issues.openmrs.org/browse/RATEST-348 @Muta-Jonathan

**Comment by kdaud** [comment]
@Muta-Jonathan change the commit ID to the one Anjula has shared.

**Pull request closed without merging**
