### PR TITLE
Setting the includes.csrftoken property

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by dkayiwa** [comment]
How different is this from these two commits? https://github.com/openmrs/openmrs-contrib-qaframework/commits/master

**Comment by sherrif10** [comment]
All tests are now breaking on GitHub actions. I don't know if @kdaud
experience it.

**Comment by kdaud** [comment]
> How different is this from these two commits? https://github.com/openmrs/openmrs-contrib-qaframework/commits/master

The changes here are adding the same property which is required in the 

1. test-local.properties for bdd tests to pass github actions, 
2. test.properties for legacy tests to pass locally
3. test-bamboo.properties for legacy tests to pass ci
4. test-loacl.properties for legacy tests to pass github actions

**Comment by sherrif10** [comment]
All the tests are in stale. @kdaud do we need to get this into master to resurrect those tests failing.

**Comment by kdaud** [comment]
> @kdaud do we need to get this into master to resurrect those tests failing.

no! 

Green should be the passport for this commit to enter master.

**Comment by sherrif10** [comment]
i can see that these changes are creating green light but without these changes , no ticket is running on github actions. are you seeing most updated tickets failing.

**Comment by kdaud** [comment]
@sherrif10 are you able to run any of the test locally using qa server or demo serve?

**Comment by sherrif10** [comment]
> are you able to run any of the test locally using qa or demo server?

Yes @kdaud  am able to simulate the instances.

**Comment by kdaud** [comment]
The test are failing out on local host and probably failing to login into the instance,  On the other hand have taken a use case to run the tests against the demo server,  qa server and they are passing the plan. If we are to switch the test to run on qa server in github action any way, all the platform tests will fail the plan.

any thought on the way forward?

**Comment by sherrif10** [comment]
> all the platform tests will fail the plan.

All platforms were passing on qa server. what exactly happened on our server.

**Comment by kdaud** [comment]
> All platforms were passing on qa server.

@sherrif10 do you mind to test this and confirm?

**Comment by kdaud** [comment]
> @kdaud tests are passing locally . Tested this

how are you running the platform tests locally?

**Comment by sherrif10** [comment]
Sorry have been testing refapp workflows not platforms .Currently platforms are failing.

**Pull request merged**
