### PR TITLE
Rename Package.json run scripts from refapp... to refApp...

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-205

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 is this PR ready for review ?

**Comment by sherrif10** [comment]
Yes @kdaud . Its ready for review. Thanks

**Comment by kdaud** [comment]
@sherrif10 have you had a look at my comment [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905381238) ?

**Comment by sherrif10** [comment]
Saw the comment. i agree we can merge them.

**Comment by kdaud** [comment]
> i agree we can merge them.

Checkout my comment [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905445026) !

**Comment by sherrif10** [comment]
What is your opinion @kdaud

**Comment by kdaud** [comment]
> What is your opinion @kdaud

IMO its not a good idea to combine changes that affects 2.x and 3.x workflow tests in one commit. It will make it hard in future to track these changes we would rather have two separate tickets to meet the requirement for 2.x and 3.x workflows respectively.

It was in my minds to create [RATEST-202 ](https://issues.openmrs.org/browse/RATEST-205) and [RATEST-205](https://issues.openmrs.org/browse/RATEST-205) in order **NOT** to mix changes related to  2.x and 3.x refapp so that we can easily track their respective changes in the future. I would not recommend to combine changes of 2.x and 3.x in one commit, and this is not a good move as I reflect in the future perspective of the project.

**Comment by sherrif10** [comment]
> IMO its not a good idea to combine changes that affects 2.x and 3.x workflow tests in one commit. It will make it hard in future to track these changes we would rather have two separate tickets to meet the requirement for 2.x and 3.x workflows respectively.

What could be the differentiation between this ticket in reference to 2.x and 3.x

**Comment by sherrif10** [comment]
cc @jayasanka-sack  would you help me understand these changes in reference to @kdaud  ticket RATEST-202. Thanks

**Comment by kdaud** [comment]
> What could be the differentiation between this ticket in reference to 2.x and 3.x

Have provided sufficient explanation in my recent comment [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905470751) !

**Comment by sherrif10** [comment]
All these tickets is all about refactoring.

**Comment by kdaud** [comment]
> All these tickets is all about refactoring.

Checkout my comment [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905476063)

**Comment by kdaud** [comment]
> shall we look into this

I want to guess that @brandones saw the conversation on this [PR](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90) and as well saw the last three comments [1](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905502918) [2](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905534914) [3](https://github.com/openmrs/openmrs-contrib-qaframework/pull/90#issuecomment-905547620) before he performed the merge action and thought fully he embraced the workflow naming convention embedded in that merged commit.

Would be glad to discuss any further suggestion(s) here so that we get  guidance from senior geeks where need be.

**Comment by sherrif10** [comment]
Sounds clear @brandones  .Thanks

**Comment by kdaud** [comment]
@sherrif10 did you take a look at the ticket requirement ? 

You might need to revisit the ticket goal/objective in ticket description section to figure out what is expected otherwise am seeing the changes in this commit are not addressing the ticket requirement !

**Comment by brandones** [comment]
I just really don't care, but you guys have obviously spent a lot of time on this trivial and meaningless change. I'm merging it so no one has to think about it again. Personally I prefer `refapp`.

**Comment by sherrif10** [comment]
> I just really don't care, but you guys have obviously spent a lot of time on this trivial and meaningless change.

I totallly agree with you @brandones.

**Comment by brandones** [comment]
Oh okay @kdaud , if you want to keep going back and forth with @sherrif10 about this, you're welcome to. And then merge it yourself. This whole thing should have taken a single developer about 30 seconds. I can't imagine why you didn't just fix it yourself, @kdaud , rather than even file a ticket for it.

**Comment by kdaud** [comment]
The changes in this commit do not address the ticket requirement, so I would not recommend merging this work until the ticket requirement has been met. I have referred @sherrif10 [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/91#issuecomment-905691368)

**Comment by brandones** [comment]
Then take the one minute to fix it like you think it should be fixed, @kdaud .

**Pull request closed without merging**
