### PR TITLE
RATEST-199:Removed feature file definitions to avoid duplicates

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-199 
What happened in this commit
Removed all the defined feature files that we nolonger need to have .These feature files already have classes in referenceapplication distro test classes. This will promote code quality and reduce resources. we are supposed not to duplicate resources.

Renamed the file folders.

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @kdaud

**Comment by HerbertYiga** [comment]
thanks @sherrif10  hoping all these were duplicates!

**Comment by kdaud** [comment]
Here is my thought !

On the one hand we can get rid of those empty feature files whose would be written selenium test functionality are already being automated by the old legacy tests. However the author might have had in mind that some functionality whose selenium legacy test did not cover some user stories on those respective functionality and thought it wise to include their feature files so that the uncovered user stories on the respective functionality are written in the new framework. Use case selenium test for visit did not cover some user stories on the the visit feature so we would need to have those uncovered use stories written in the new framework.

More of my thought are captured in the 2rd, 3rd and 4th  paragraphs [here](https://talk.openmrs.org/t/missing-feature-and-step-definition-files/34201/5)

**Comment by sherrif10** [comment]
Visitnote test covered all required user stories

**Comment by sherrif10** [comment]
Sure , thanks @herbert

**Comment by kdaud** [comment]
> Visitnote test covered all required user stories

 I think there is a difference between `visit` I cited in the user case [above ](https://github.com/openmrs/openmrs-contrib-qaframework/pull/85#issuecomment-902476588) and `Visitnote`. @sherrif10 do you think these functionalities are the same ?

**Comment by sherrif10** [comment]
Starting a visit is different from visit note however if the functionality
is relatively to capturing obs from visitnote.we need to update that
probably

**Comment by kdaud** [comment]
The `Visit` in this context is ideally referencing what a clinician can do while on a Patient Dashboard Page. In short `startVist` `AddVisit`, `MergeVist`, `VisitNote` and `others` in the same category are nodes of `Visit `

Dashboard

**Comment by sherrif10** [comment]
I agree with you, Will add visit folder and feature file back, then we shall handle that in future, however we have visitTypes and visit and i guess this is handling same thing.

**Comment by sherrif10** [comment]
Thanks @kdaud .

**Comment by kdaud** [comment]
@sherrif10 before you merged the commit did you ensure to have read very well my comment [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/85#issuecomment-902476588) ? The commit was not yet worth to be merged because they were things to consider as I tried to shade a light on why some feature files should not be removed.

BTW @dkayiwa advised us not to merge commits until the reviewer approves the commit and then tags geeks for their final reviews.  Its very important to consider advised given to us by senior developers as we take the advantage to learn from them!

I would love to hear what @dkayiwa has to say about this otherwise if this is the direction we are heading then there is danger a head !

**Comment by dkayiwa** [comment]
@sherrif10 did you merge this accidentally without approval?

**Comment by sherrif10** [comment]
ohh my bad, sorry about that. Sure @dkayiwa @kdaud

**Comment by dkayiwa** [comment]
Reverted at: https://github.com/openmrs/openmrs-contrib-qaframework/pull/86

**Comment by sherrif10** [comment]
Thanks @dkayiwa for revert @kdaud Are you still having concerns /suggestions regarding this not to be merged, am still confident enough this is fine to be merged

**Comment by sherrif10** [comment]
cc @kdaud .Looking forward for approval or more suggestions.Thanks.

**Comment by kdaud** [comment]
Revisit my review [above](https://github.com/openmrs/openmrs-contrib-qaframework/pull/85#issuecomment-902476588)

Additionally Ideally recommend we first identify functionalities for 2.x RefApp that were not covered by selenium legacy tests in [distro](https://github.com/openmrs/openmrs-distro-referenceapplication/tree/master/ui-tests/src/test/java/org/openmrs/reference) and then create tickets for contributors to handle them then latter we can then get rid of the empty feature files that do not qualify otherwise getting rid of them should not be a priority for now. 

Its our responsibility to look through the 2.x RefApp functionality that were not covered to avail tickets that are worth to be worked on by the contributors otherwise have already seen PRs  from contributors working on issues that were created on the QA Jira [Dashboard](https://issues.openmrs.org/secure/RapidBoard.jspa?rapidView=240&selectedIssue=RATEST-186) for the new test workflows from contributors that are not worth solving !

We can always arrange for this call perhaps probably immediately after QA Calls for 20 minutes proposing  from 8:00pm  -8:20pm so that we do a back log for the tasks then we avail them on the our Dashboard. This will help our contributors not to waste efforts on tasks that are not worth solving. 

@sherrif10  what is your thought  ?

**Comment by sherrif10** [comment]
Lets understand things clear and be on same plate, some feature files need to be created forexample admitToInpatient, this need to be captured and gracebish is working on it, For this commit was to  remove those feature files that we really dont have, can we start from there

**Comment by kdaud** [comment]
> some feature files need to be created forexample admitToInpatient, this need to be captured and gracebish is working on it

Did you get a chance to see my comment [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/75#issuecomment-902108702) ?

**Pull request merged**
