### PR TITLE
NEW E2E: Data Management WorkFlow

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-197

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @kdaud  ,Looking for reviews Thanks

**Comment by kdaud** [comment]
Take a look at the tests [MergePatestTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/MergePatientTest.java) and [MergePatientSteps ](https://github.com/openmrs/openmrs-contrib-qaframework/blob/a1890e98637628b4bd58fcf31bc7e0c70d0cf86d/src/test/java/org/openmrs/contrib/qaframework/automation/MergePatientSteps.java). 

WDYT ?

**Comment by sherrif10** [comment]
Ohh sure, do you have any suggestion, The reason i had is to have this written in a new BDD  approach and a new framework. looking forward for your suggestions .Thanks

**Comment by kdaud** [comment]
I gave a recommendation [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/75#issuecomment-901292507) as well on the public talk post [1](https://talk.openmrs.org/t/missing-feature-and-step-definition-files/34201/5) [2](https://talk.openmrs.org/t/missing-feature-and-step-definition-files/34201/6). A community member as well gave a recommendation [here](https://talk.openmrs.org/t/missing-feature-and-step-definition-files/34201/10)

**Pull request closed without merging**
