### PR TITLE
Organising Feature files in refapp-2.x

### PR DESCRIPTION
**Pull request by mherman22**
**Ticket ID**
https://issues.openmrs.org/browse/RATEST-269

**Description**
The purpose of this pull request is to delete the spaces within the scenarios in the feature files

**Reference**
#174

**Things done to that effect**
i have deleted the spaces in each of the scenarios
cc : @kdaud

### CODE REVIEW

**Comment by sherrif10** [comment]
@mherman22  Make sure you only have changes that are required by this ticket.

**Comment by mherman22** [comment]
> @mherman22 Make sure you only have changes that are required by this ticket.

hey @sherrif10 thanks. could you guide me on that. 
The conditions feature file whch is part of what am supposed to do belongs to another branch RATEST-242 which has all those other commits.

**Comment by kdaud** [comment]
@mherman22 reset your branch to master and then make your changes regarding this ticket.

**Comment by sherrif10** [comment]
i agree with @kdaud

**Comment by HerbertYiga** [comment]
and you squash your commits too @mherman22

**Pull request closed without merging**
