### PR TITLE
RATEST-193: Add windows execution configuration to support devs using  windows os

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/projects/RATEST/issues/RATEST-193)
Description -> : Add windows execution configuration to support devs using  windows os

### CODE REVIEW

**Comment by sherrif10** [comment]
Well done @kdaud

**Review by mherman22 — COMMENTED** [review]
great work @kdaud

**Review by mherman22 — COMMENTED** [review]
great work @kdaud

**Comment by sherrif10** [comment]
Hop everything is fine now

**Pull request merged**
