### PR TITLE
Bump chromedriver from 90.0.44 -> 99.0.48 to fix Bamboo failures

### PR DESCRIPTION
**Pull request by kdaud**
Currently ci plans are failing due to the failure of instantiating the old chrome driver hence upgrading the driver version.

See logs at https://ci.openmrs.org/browse/CONTRIB-QA-FRAMEWORK-1628/log

### CODE REVIEW

**Comment by sherrif10** [comment]
Have you updated the chrome version.

**Comment by kdaud** [comment]
Have upgraded driver version as mentioned in the description section above.

**Comment by sherrif10** [comment]
is that the current version of chrome ?

**Comment by kdaud** [comment]
The current version is 104.0.51 but most likely not supported by Bamboo agent we are using.

**Comment by kdaud** [comment]
Have upgraded to the latest driver version

**Comment by kdaud** [comment]
@sherrif10 the current version is not being supported by Bamboo, so we need to a lower version probably the one suggested earlier on (v99.0.48)

**Comment by sherrif10** [comment]
We can try out the later version.

**Comment by kdaud** [comment]
Which [version](https://chromedriver.chromium.org/downloads) could we try out?

**Pull request merged**
