### PR TITLE
Added Build Statuses for Trunk, RESTWS, FHIR2, & LU

### PR DESCRIPTION
**Pull request by gracepotma**
Goal: To add these status items into our QA dashboard. (This actually helped catch a failing platform build before even the Talk items did!)
image

Result: 
image

### CODE REVIEW

**Comment by gracepotma** [comment]
@kdaud @sherrif10 are you happy with this?

**Review by sherrif10 — APPROVED** [review]
LGTM

**Comment by kdaud** [comment]
Thanks @gracepotma for the technical work you do with the QA team/squad !

Thanks for adding Trunk, RESTWS, FHIR2, and LU on the QA Dashboard. Two things I would love to know

1. For the added modules, are the budges showing the unit/integration tests status or E2E tests for those modules or not tracking tests at all?
2. Is the Build status for the modules tracked from their latest Bamboo build plan for those respective modules ?

One thought here;
We can have more modules added on the QA Dashboard to track their status especially those that are very vital to our work. cc: @sherrif10

**Comment by ibacher** [comment]
> For the added modules, are the budges showing the unit/integration tests status or E2E tests for those modules or not tracking tests at all?

Basically, it's the status of the Bamboo builds which also includes any tests in those builds.

> Is the Build status for the modules tracked from their latest Bamboo build plan for those respective modules ?

Yes

**Comment by kdaud** [comment]
Thanks @ibacher, have sweetly learnt it and now a consultant to myself!

**Comment by HerbertYiga** [comment]
> Basically, it's the status of the Bamboo builds which also includes any tests in those builds.

sure,thanks @ibacher

**Pull request merged**
