### PR TITLE
O3-895: Update E2E workflows to generate a cucumber report

### PR DESCRIPTION
**Pull request by pasindur99**
## Purpose
The pull request is to fix -
Issue ticket [O3-895](https://issues.openmrs.org/browse/O3-895)

## Goals
Generate cucumber reports for E2E workflows

## Approach
1. Enable cucumber to store the test results in cucumber.properties in each 3.X workflows.
2. Create a script that will publish the result to cucumber studio

### CODE REVIEW

**Comment by sherrif10** [comment]
@pasindur99 is this pr up to date with master.

**Comment by pasindur99** [comment]
@sherrif10 I updated this pr with the master branch. There's a small blocker with this pr. Once I fix it I will mark this as ready for review. 
cc: @jayasanka-sack

**Comment by sherrif10** [comment]
That sounds awesome

**Comment by kdaud** [comment]
Update this PR with changes from master

**Comment by pasindur99** [comment]
@kdaud Currently we are updating the workflows to dockerize the E2E tests environments. once that task is over I will make this pr as ready for review! Thank you!

**Comment by sherrif10** [comment]
@pasindur99  are you still interested in this pull request.

**Pull request closed without merging**
