### PR TITLE
Re build the index

### PR DESCRIPTION
**Pull request by sherrif10**

### CODE REVIEW

**Comment by sherrif10** [comment]
cc @kdaud coud we use this simple rebuid index to track the building of our badges

**Comment by kdaud** [comment]
> could we use this simple rebuild index to track the building of our badges

what do you mean by the caption above?

**Comment by sherrif10** [comment]
Could you merge this commit and we see if this could help in resurrecting the failing tests.

**Comment by kdaud** [comment]
which failing tests the PR fixing?

**Comment by sherrif10** [comment]
The intension is to triggger the failing builds.Nothing much

**Comment by kdaud** [comment]
Have run all the workflows manually;  RefApp 2.x tests passed though platform UI tests are failing
Screenshot from 2021-12-23 16-52-41

**Comment by sherrif10** [comment]
Thats great.

**Pull request closed without merging**
