### PR TITLE
Bump selenium version from 4.1.2 to 4.0-alpha-6

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by dkayiwa** [comment]
I completely agree with @sherrif10 on this one. The old drivers had a bug which resulted into the actual failure error details not being shown in the logs. It is very hard to fix failing tests without full failure details in the logs.

**Comment by kdaud** [comment]
> Do they fail even with `includes.csrftoken` set to `false`?

Will give feedback on this once I execute the use case.


> Did you exhaust all possible options of fixing this without downgrading?

Am continuing to explore the other possible options 


> You can look at this for more details: [SeleniumHQ/selenium#9784](https://github.com/SeleniumHQ/selenium/issues/9784)

Thanks @dkayiwa for the link. I have quickly skimmed it through and the use case here is similar to what other folks have ever faced so its helpful. @sherrif10 have you gone through the thread?

**Comment by sherrif10** [comment]
@kdaud  do we still need this commit. i saw another  pull here https://github.com/openmrs/openmrs-contrib-qaframework/pull/360  
if my @dkayiwa  suggestions above. is it possible have them in this commit and we get rid of what is not needed.

**Comment by kdaud** [comment]
Based on the conversation on this commit, the suggested solution here is overridden by other better possible options hence pull/360.

**Pull request closed without merging**
