### PR TITLE
RATEST-183: Upgrade chrome driver for linux os from 88.0.4 to 91.0.4

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-183)
Description -> Upgrade chrome driver for linux os to 91.0.4

### CODE REVIEW

**Comment by dkayiwa** [comment]
Which version are you upgrading it from?

**Comment by kdaud** [comment]
> Which version are you upgrading it from?

Have updated the commit title accordingly!

**Comment by kdaud** [comment]
@dkayiwa have added the drivers for windows os in this [PR](https://github.com/openmrs/openmrs-contrib-qaframework/pull/65)

**Comment by sherrif10** [comment]
This is awesome, Would you mind creating a single pull request that handles the two with this ,https://github.com/openmrs/openmrs-contrib-qaframework/pull/65

**Comment by sherrif10** [comment]
is this version of chrome the latest version of chrome

**Comment by kdaud** [comment]
> This is awesome, Would you mind creating a single pull request that handles the two with this ,#65

I'm of two minds!
One the one hand, making a grand PR combining both commit seems ok!

On the other hand, separating the PR as of now since we need to track what each commit addressed. One is addressing adding drivers of windows os in the repo and the other is upgrading chrome driver version of linux os. Though both of them are in line with drivers but they are relatively addressing different concerns. Separating them overrides making a grand PR!

**Comment by kdaud** [comment]
cc: @dkayiwa

**Comment by kdaud** [comment]
Once again this is @kdaud. 
After investigating  the current build failures of our [OpenMRS QA Framework ](https://ci.openmrs.org/browse/CONTRIB-QA-714)  I noticed the following!
Bamboo build for OpenMRS QA Framework spins from chrome driver and is certainly set to use a specific driver version that was recently used before the changes of this commit. At the moment have not figured out where the configuration of these setting that specified the chrome version are sited but will get time and investigate them.

So its from the reason above I recommend we revert back to the previous version. Good enough any one can always change the `wedriver` version to suit the chrome version that runs on his/her machine for local simulation(testing) and BTW we can not cater for all version since every one may opt for a different version. 

Based on the reason above, am waiting to see an action that reverts the commit !
cc: @sherrif10 @dkayiwa

**Comment by kdaud** [comment]
Green Every where! Bamboo builds are green for Distribuition, UI and OpenMRS QA framework.
Green

cc: @sherrif10 @dkayiwa

**Pull request merged**
